### ISSUE TITLE
Extensions and mechanisms

### ISSUE THREAD

**Issue by Maroca** [Pkcs11Interop/Pkcs11Interop#111]
Hi Pkcs11Interop team!,

I'm looking for information about extensions and how implement custom mechanisms to my pkcs11 project.

I've followed #36  and it was a nice reference, but i cant find examples about custom mechanism implementation. 

So i need to pass as a parameter with an struct with some byte arrays. I suppose it is needed a struct with IMechanismParams interface (to implement ToMarshableStructure)

But Im stucked at this point.

Can you help me with this issue?

Thanks in advance.

**Comment by jariq** [comment]
Could you please provide more details about the mechanism you are trying to add? It would be great if you could at least paste C definitions of its parameters.

**Comment by jariq** [comment]
Note that this answer applies to current stable version [Pkcs11Interop 4.1.0](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/4.1.0).

In general to define new mechanism parameters you should:
1. Find similar `struct` in [official C header](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/headers/pkcs11t.h)
2. Find its counterpart in [LowLevelAPI](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/4.1.0/src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI41/MechanismParams), study and understand its code
3. Find its counterpart in [HighLevelAPI](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/4.1.0/src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI41/MechanismParams), study and understand its code
4. Use acquired knowledge to add your own structs to LowLevelAPIs
5. Use acquired knowledge to add your own classes to HighLevelAPIs

To get you started let's look at the two structs you have posted here:

You first need to rewrite these C structs into C# structs located in LowLeveAPIs. If you're going to use them only on Windows then `LowLevelAPI41` is all you need:

```csharp
using System;
using System.Runtime.InteropServices;

namespace Net.Pkcs11Interop.LowLevelAPI41.MechanismParams
{
    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)]
    public struct CK_INITIALIZE_PARAMS
    {
        public CK_AUTH_DATA AuthData;
        [MarshalAs(UnmanagedType.U1)]
        public bool Assigned;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Unicode)]
    public struct CK_AUTH_DATA
    {
        public uint ModulusLen;
        public IntPtr Modulus;
        public uint PublicExponentLen;
        public IntPtr PublicExponent;
        public byte Protocol;
    }
}
```

After that you can create more convenient classes in HighLevelAPIs. Again if you're going to use them only on Windows then `HighLevelAPI41` is all you need:

```csharp
using System;
using Net.Pkcs11Interop.Common;
using Net.Pkcs11Interop.LowLevelAPI41.MechanismParams;

namespace Net.Pkcs11Interop.HighLevelAPI41.MechanismParams
{
    public class CkInitializeParams : IMechanismParams
    {
        private CK_INITIALIZE_PARAMS _lowLevelStruct = new CK_INITIALIZE_PARAMS();

        private CkAuthData _authData = null;

        public CkInitializeParams(CkAuthData authData, bool assigned)
        {
            if (authData == null)
                throw new ArgumentNullException("authData");

            // Keep reference to randomInfo so GC will not free it while this object exists
            _authData = authData;

            _lowLevelStruct.AuthData = (CK_AUTH_DATA)_authData.ToMarshalableStructure();
            _lowLevelStruct.Assigned = assigned;
        }

        #region IMechanismParams

        /// <summary>
        /// Returns managed object that can be marshaled to an unmanaged block of memory
        /// </summary>
        /// <returns>A managed object holding the data to be marshaled. This object must be an instance of a formatted class.</returns>
        public object ToMarshalableStructure()
        {
            return _lowLevelStruct;
        }

        #endregion
    }

    public class CkAuthData : IMechanismParams, IDisposable
    {
        private bool _disposed = false;

        private CK_AUTH_DATA _lowLevelStruct = new CK_AUTH_DATA();

        public CkAuthData(byte[] modulus, byte[] publicExponent, byte protocol)
        {
            if (modulus != null)
            {
                _lowLevelStruct.Modulus = UnmanagedMemory.Allocate(modulus.Length);
                UnmanagedMemory.Write(_lowLevelStruct.Modulus, modulus);
                _lowLevelStruct.ModulusLen = Convert.ToUInt32(modulus.Length);
            }

            if (publicExponent != null)
            {
                _lowLevelStruct.PublicExponent = UnmanagedMemory.Allocate(publicExponent.Length);
                UnmanagedMemory.Write(_lowLevelStruct.PublicExponent, publicExponent);
                _lowLevelStruct.PublicExponentLen = Convert.ToUInt32(publicExponent.Length);
            }

            _lowLevelStruct.Protocol = protocol;
        }

        #region IMechanismParams

        /// <summary>
        /// Returns managed object that can be marshaled to an unmanaged block of memory
        /// </summary>
        /// <returns>A managed object holding the data to be marshaled. This object must be an instance of a formatted class.</returns>
        public object ToMarshalableStructure()
        {
            if (this._disposed)
                throw new ObjectDisposedException(this.GetType().FullName);

            return _lowLevelStruct;
        }

        #endregion

        #region IDisposable

        /// <summary>
        /// Disposes object
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Disposes object
        /// </summary>
        /// <param name="disposing">Flag indicating whether managed resources should be disposed</param>
        protected virtual void Dispose(bool disposing)
        {
            if (!this._disposed)
            {
                if (disposing)
                {
                    // Dispose managed objects
                }

                // Dispose unmanaged objects
                UnmanagedMemory.Free(ref _lowLevelStruct.Modulus);
                _lowLevelStruct.ModulusLen= 0;

                UnmanagedMemory.Free(ref _lowLevelStruct.PublicExponent);
                _lowLevelStruct.PublicExponentLen = 0;

                _disposed = true;
            }
        }

        /// <summary>
        /// Class destructor that disposes object if caller forgot to do so
        /// </summary>
        ~CkAuthData()
        {
            Dispose(false);
        }

        #endregion
    }
}
```

Now that you have convenient classes available for your custom mechanism parameters, all you need to do is define your custom mechanism as `ulong CKM_INITIALIZE = 0x8000C951;` and use it with correct method that is already present in Pkcs11Interop or extend Pkcs11Interop with new method as described in #36.

Hope this helps.

**Comment by Maroca** [comment]
My most sincere gratitude, I will work with what you've said and I will be putting the results in this thread.

At the moment, i was closely about your response. I've decided to extend SessionClassExtension to add the required methods of c:

```
typedef int(__stdcall * pKeyAuthorizationInit)(
		CK_SESSION_HANDLE hSession,    /* the session's handle */
		CK_MECHANISM_PTR  pMechanism,  /* the authorization mechanism */
		CK_OBJECT_HANDLE  hKey,        /* handle of  key */
		CK_BYTE_PTR       pHash,       /* gets the hash */
		CK_ULONG_PTR      pulHashLen   /* gets hash length */
		);
typedef int(__stdcall * pKeyAuthorization)(
		CK_SESSION_HANDLE hSession,        /* the session's handle */
		CK_BYTE_PTR       pSignature,      /* the signature */
		CK_ULONG          ulSignatureLen   /* the signature length */
		);
```

I think I need to define correctly these methods, with proper pointers etc etc... because always give me the same result (rv=112) CKR_MECHANISM_INVALID

this is probably incorrect because Mechanism is a ptr on C definition
```
#region HighLevelAPI extensions

        public static void KeyAuthorization(this Session session, IntPtr pSignature, uint ulSignature)
        {
            session.HLA41Session.KeyAuthorization(pSignature, ulSignature);
        }

        public static void KeyAuthorizationInit(this Session session, Mechanism mechanism, uint objectHandle, IntPtr pHash, IntPtr pulHashLen)
        {
            session.HLA41Session.KeyAuthorizationInit(mechanism, objectHandle, pHash,pulHashLen);
        }
        
        #endregion

#region HighLevelAPI4x and HighLevelAPI8x extensions

        public static void KeyAuthorization(this HLA41.Session session, IntPtr pSignature, uint ulSignature)
        {
            CKR rv = session.LowLevelPkcs11.C_KeyAuthorization(session.SessionId,pSignature,ulSignature);
            if (rv != CKR.CKR_OK)
                throw new Pkcs11Exception("C_KeyAuthorization", rv);
        }
        public static void KeyAuthorizationInit(this HLA41.Session session, Mechanism mechanism, uint hKey, IntPtr pHash, IntPtr pulHashLen)
        {
            CKR rv = session.LowLevelPkcs11.C_KeyAuthorizationInit(session.SessionId, mechanism, hKey, pHash, pulHashLen);
            if (rv != CKR.CKR_OK)
                throw new Pkcs11Exception("C_KeyAuthorizationInit", rv);
        }

#endregion

#region LowLevelAPI4x and LowLevelAPI8x extensions

        /// <summary>
        /// Delegates for vendor specific unmanaged method
        /// </summary>
        private static class Delegates
        {

            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            internal delegate uint C_KeyAuthorization4x(uint session, IntPtr pSignature, uint ulSignature); 

            [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
            internal delegate uint C_KeyAuthorizationInit4x(uint session, ref Mechanism pMechanism, uint hKey, IntPtr pHash, IntPtr pulHashLen);
        }

        public static CKR C_KeyAuthorization(this LLA41.Pkcs11 pkcs11, uint session, IntPtr pSignature, uint ulSignature)
        {
            if (pkcs11.Disposed)
                throw new ObjectDisposedException(pkcs11.GetType().FullName);

            Delegates.C_KeyAuthorization4x cKeyAuthorization = null;

            if (pkcs11.LibraryHandle != IntPtr.Zero) {
                IntPtr cKeyAuthorizationPtr = UnmanagedLibrary.GetFunctionPointer(pkcs11.LibraryHandle, "C_KeyAuthorization");
                cKeyAuthorization = UnmanagedLibrary.GetDelegateForFunctionPointer<Delegates.C_KeyAuthorization4x>(cKeyAuthorizationPtr);
            } 

            uint rv = cKeyAuthorization(session, pSignature, ulSignature);
            return (CKR)rv;
        }
        
        public static CKR C_KeyAuthorizationInit(this LLA41.Pkcs11 pkcs11, uint session, Mechanism mechanism, uint hKey, IntPtr pHash, IntPtr pulHashLen)
        {
            if (pkcs11.Disposed)
                throw new ObjectDisposedException(pkcs11.GetType().FullName);

            Delegates.C_KeyAuthorizationInit4x cKeyAuthorizationInit = null;

            if (pkcs11.LibraryHandle != IntPtr.Zero) {
                IntPtr cKeyAuthorizationInitPtr = UnmanagedLibrary.GetFunctionPointer(pkcs11.LibraryHandle, "C_KeyAuthorizationInit");
                cKeyAuthorizationInit = UnmanagedLibrary.GetDelegateForFunctionPointer<Delegates.C_KeyAuthorizationInit4x>(cKeyAuthorizationInitPtr);
            }
            

            uint rv = cKeyAuthorizationInit(session,ref mechanism, hKey, pHash, pulHashLen);

            return (CKR)rv;
        }

#endregion
```
Still working on it

Thanks for your time, again. 

Best regards.

**Comment by jariq** [comment]
Your `C_KeyAuthorizationInit` and `C_KeyAuthorization` methods use similar parameters as standard [`C_SignInit`](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/4.1.0/src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI41/Pkcs11.cs#L854-L861) and [`C_Sign`](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/4.1.0/src/Pkcs11Interop/Pkcs11Interop/LowLevelAPI41/Pkcs11.cs#L875-L882) methods so definitely take a look at their implementation.

**Comment by Maroca** [comment]
I think i've got the correct configuration to call these methods. 

But the log of pkcs11 library allways throws me an error:
```
[00006B4C:00000504] p11::ErrorCode::mapToP11         | E: error 0xb0680314 mapped.
[00006B4C:00000504] C_KeyAuthorization             | E: Error CKR_GENERAL_ERROR occurred.
```

I still working on it, but i dont have any idea why is this happening (in c++ works fine). Probably I misses some step or something to send the correct data.

Later I will post the completely classes for help on comunity.


Thanks for yours advices and knwoldege ;)
Best regards

**Comment by Maroca** [comment]
`//namespace Net.Pkcs11Interop.HighLevelAPI41.MechanismParams

    public class CkInitializeParams : IMechanismParams
    {
        public CK_CP5_INITIALIZE_PARAMS _lowLevelStruct = new CK_CP5_INITIALIZE_PARAMS();

        private CkAuthData _authData = null;

        public CkInitializeParams(CkAuthData authData, bool assigned)
        {
            if (authData == null)
                throw new ArgumentNullException("authData");

            // Keep reference to randomInfo so GC will not free it while this object exists
            _authData = authData;

            _lowLevelStruct.AuthData = (CK_CP5_AUTH_DATA)_authData.ToMarshalableStructure();
            _lowLevelStruct.Assigned = assigned;
        }

        #region IMechanismParams

        /// <summary>
        /// Returns managed object that can be marshaled to an unmanaged block of memory
        /// </summary>
        /// <returns>A managed object holding the data to be marshaled. This object must be an instance of a formatted class.</returns>
        public object ToMarshalableStructure()
        {
            return _lowLevelStruct;
        }

        #endregion
    }

    public class CkAuthorizeParams : IMechanismParams
    {
        private CK_CP5_AUTHORIZE_PARAMS _lowLevelStruct = new CK_CP5_AUTHORIZE_PARAMS();

        public CkAuthorizeParams(uint ulCount = 0)
        {
            _lowLevelStruct.UlCount = ulCount;
        }

        #region IMechanismParams

        /// <summary>
        /// Returns managed object that can be marshaled to an unmanaged block of memory
        /// </summary>
        /// <returns>A managed object holding the data to be marshaled. This object must be an instance of a formatted class.</returns>
        public object ToMarshalableStructure()
        {
            return _lowLevelStruct;
        }

        #endregion
    }

    public class CkAuthData : IMechanismParams, IDisposable
    {
        private bool _disposed = false;

        private CK_CP5_AUTH_DATA _lowLevelStruct = new CK_CP5_AUTH_DATA();

        public CkAuthData(byte[] modulus, byte[] publicExponent, byte protocol)
        {
            if (modulus != null) {
                _lowLevelStruct.Modulus = UnmanagedMemory.Allocate(modulus.Length);
                UnmanagedMemory.Write(_lowLevelStruct.Modulus, modulus);
                _lowLevelStruct.ModulusLen = Convert.ToUInt32(modulus.Length);
            }

            if (publicExponent != null) {
                _lowLevelStruct.PublicExponent = UnmanagedMemory.Allocate(publicExponent.Length);
                UnmanagedMemory.Write(_lowLevelStruct.PublicExponent, publicExponent);
                _lowLevelStruct.PublicExponentLen = Convert.ToUInt32(publicExponent.Length);
            }

            _lowLevelStruct.Protocol = protocol;
        }

        #region IMechanismParams

        /// <summary>
        /// Returns managed object that can be marshaled to an unmanaged block of memory
        /// </summary>
        /// <returns>A managed object holding the data to be marshaled. This object must be an instance of a formatted class.</returns>
        public object ToMarshalableStructure()
        {
            if (this._disposed)
                throw new ObjectDisposedException(this.GetType().FullName);

            return _lowLevelStruct;
        }

        #endregion

        #region IDisposable

        /// <summary>
        /// Disposes object
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        /// <summary>
        /// Disposes object
        /// </summary>
        /// <param name="disposing">Flag indicating whether managed resources should be disposed</param>
        protected virtual void Dispose(bool disposing)
        {
            if (!this._disposed) {
                if (disposing) {
                    // Dispose managed objects
                }

                // Dispose unmanaged objects
                UnmanagedMemory.Free(ref _lowLevelStruct.Modulus);
                _lowLevelStruct.ModulusLen = 0;

                UnmanagedMemory.Free(ref _lowLevelStruct.PublicExponent);
                _lowLevelStruct.PublicExponentLen = 0;

                _disposed = true;
            }
        }

        /// <summary>
        /// Class destructor that disposes object if caller forgot to do so
        /// </summary>
        ~CkAuthData()
        {
            Dispose(false);
        }

        #endregion
    }


//namespace Net.Pkcs11Interop.LowLevelAPI41.MechanismParams

    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Ansi)]
    public struct CK_CP5_INITIALIZE_PARAMS
    {
        public CK_CP5_AUTH_DATA AuthData;
        [MarshalAs(UnmanagedType.U1)]
        public bool Assigned;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Ansi)]
    public struct CK_CP5_AUTH_DATA
    {
        public uint ModulusLen;
        public IntPtr Modulus;
        public uint PublicExponentLen;
        public IntPtr PublicExponent;
        public byte Protocol;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Ansi)]
    public struct CK_CP5_AUTHORIZE_PARAMS
    {
        public uint UlCount;
    }

`

Sorry, I thought I posted this years ago. I'm really sorry
