### ISSUE TITLE
How to impletement RSA-PSS

### ISSUE THREAD

**Issue by yawarkhan15** [Pkcs11Interop/Pkcs11Interop#113]
Hi Team, I have a requirement where I need to use RSA-PSS with out hashing can u please help me out with it.

**Comment by jariq** [comment]
Take a look at [Pkcs11RsaProvider](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/0.2.0/src/Pkcs11Interop.X509Store/Pkcs11RsaProvider.cs#L87-L98) class in [Pkcs11Interop.X509Store](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store) project for an example.

**Comment by yawarkhan15** [comment]
I have already gone through that but the problem here is we need to use hashing algorithm i.e SHA1, SHA256 etc.., Is there any way where we dont use any hashing algorithm for RSASSA-PSS

**Comment by jariq** [comment]
I'm afraid I'm not able to answer your question. Your best bet is to read chapter `12.1.9 PKCS#1 RSA PSS mechanism parameters` and chapter `12.1.10 PKCS#1 RSA PSS` of [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/raw/master/v2.20/pkcs-11v2-20.pdf) as those two chapters provide full description of RSA-PSS related PKCS#11 APIs.
