### ISSUE TITLE
IvBits in CK_GCM_PARAMS causes error when using AES GCM decrypt with cryptoki.dll

### ISSUE THREAD

**Issue by rliao-gilmond** [Pkcs11Interop/Pkcs11Interop#126]
I understand the [latest PKCS11 specification](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850506) does not specify 'IvBits' for AES GCM decryption, but it is present in the pkcs11t.h header file. The issue I'm encountering however, is that including it causes a 'param mechanism' invalid error when using the cryptoki.dll PKCS11 library from Gemalto (SafeNet HSM) to do AES GCM decryption. Since the CK_GCM_PARAMS struct gets turned into a pointer, the 'IvBits' field adds 4 more bytes to that pointer and the cryptoki library doesn't know how to handle it. When I exclude the 'IvBits' field in CK_GCM_PARAMS the issue goes away.

**Comment by jariq** [comment]
It's sad but this is one of many known issues of PKCS#11 v2.40 specification.

Let me sum it up:

[PKCS#11 v2.40 Errata 01 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.40/pkcs11-curr-v2.40-errata01-os-complete.pdf?raw=true) defines `CK_GCM_PARAMS_PTR` in chapter 2.12.3 without `ulIvBits` member as:

```c
typedef struct CK_GCM_PARAMS {
    CK_BYTE_PTR       pIv;
    CK_ULONG          ulIvLen;
    CK_BYTE_PTR       pAAD;
    CK_ULONG          ulAADLen;
    CK_ULONG          ulTagBits;
} CK_GCM_PARAMS;
```

At the same time however [PKCS#11 v2.40 Errata 01 headers](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.40/headers/pkcs11t.h)  define  `CK_GCM_PARAMS_PTR` with `ulIvBits` member as:

```c
typedef struct CK_GCM_PARAMS {
    CK_BYTE_PTR       pIv;
    CK_ULONG          ulIvLen;
    CK_ULONG          ulIvBits;
    CK_BYTE_PTR       pAAD;
    CK_ULONG          ulAADLen;
    CK_ULONG          ulTagBits;
} CK_GCM_PARAMS;
```

I notified PKCS#11 Technical Committee about this specific issue (listed as `MAJOR ISSUE #1`) and many others [three years ago](https://lists.oasis-open.org/archives/pkcs11-comment/201602/msg00001.html) but they don't seem to give a 💩. They "addressed" the issues in ["P11 2.40 Errata Comment - TC Response"](https://www.oasis-open.org/committees/document.php?document_id=58032&wg_abbrev=pkcs11) document where all problems were resolved with "No change" decision without any reasonable explanation. In all their incompetence they didn't forget to note that:

> The header files contain the normative definition.

So taking all these things into the account I currently see no reason to remove `ulIvBits` member from Pkcs11Interop library. If you need to use `CK_GCM_PARAMS` without it you can define modified version of this struct/class in your code.

**Comment by rliao-gilmond** [comment]
Thank you for detailing the history of this. It is sad and disappointing that they just don't care. I guess I will modify this for our own project.

**Comment by LudovicRousseau** [comment]
I now understand the problem.

I can't find a documentation of the `ulIvBits` field. Is it the length of IV in bits?

I also note that `CK_AES_GCM_PARAMS` was introduced in PKCS#11 2.30 header and deprecated in 2.40 to be replaced by `CK_GCM_PARAMS`.
`CK_AES_GCM_PARAMS` already had the `ulIvBits` field but is not documented in 2.30. Only `CK_GCM_PARAMS` (without `ulIvBits`) is documented in 2.30 bit not present in the header file for 2.30.

If "The header files contain the normative definition." then we have no choice but to adapt. Stupid specification.

**Comment by rliao-gilmond** [comment]
> I can't find a documentation of the `ulIvBits` field. Is it the length of IV in bits?

It seems that's the intention? However, I don't see why it is there considering there is already `ulIvLen`, the length of the the IV in bytes.

The PKCS#11 committee ought to put something on their website about these discrepancies and which is the 'normative definition'.
