### ISSUE TITLE
derive with CKM_CONCATENATE_DATA_AND_BASE does't work as expected

### ISSUE THREAD

**Issue by misaqsaadat** [Pkcs11Interop/Pkcs11Interop#129]
Hello.

I have a key with type `CKK_GENERIC_SECRET` and custom length (my real usage key size is 48 bytes). When I try to Derive it with mechanism `CKM_CONCATENATE_DATA_AND_BASE` it looks like do something wired.

Assume that my key (BASE) is `11 22 33 44 55 66 77 88` and I try to Derive it with data `00` and mechanism `CKM_CONCATENATE_DATA_AND_BASE`. My expected result is a 9 byte key with value `00 11 22 33 44 55 66 77 88` but generated and stored key is `00 11 22 33 44 55 66 77`. It seems last byte dropped so that key size doesn't change. Specifying key length in Derive method doesn't change result.

When I try to derive a key with type `CKK_GENERIC_SECRET` (and with or without specifying length) as described [here](https://www.cryptsoft.com/pkcs11doc/v211/group__SEC__12__41__3__CONCATENATION__OF__DATA__AND__A__BASE__KEY.html) if no key size specified then "Its length will be equal to the sum of the lengths of the data and the value of the original key".

PS: Because of same bug `CKM_CONCATENATE_BASE_AND_DATA` doesn't work at all. Because since key size of derived key is equal to key size of original key all of data is added to end of key will drop.

Code sample:

```csharp
static void PkcsTest()
{
	string p11lib = "_pkcs11.dll";
	var factories = new Pkcs11InteropFactories();
	var library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, p11lib, AppType.MultiThreaded);
	var slots = library.GetSlotList(SlotsType.WithTokenPresent);
	var slot = slots[0];
	var session = slot.OpenSession(SessionType.ReadWrite);
	session.Login(CKU.CKU_USER, "123456");

	var data = new byte[] { 0x68, 0x65, 0x6c, 0x6c, 0x6f };
	var originalKey = new byte[]{0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x11,0x22,0x33,0x44,0x55,0x66,0x77,0x88,0x99};
	var dataToAddToKey = new byte[] { 0x00 };
	//Import key to HSM
	var objectAttributes = new List<IObjectAttribute>
	{
		session.Factories.ObjectAttributeFactory.Create(CKA.CKA_CLASS, CKO.CKO_SECRET_KEY),
		session.Factories.ObjectAttributeFactory.Create(CKA.CKA_KEY_TYPE, CKK.CKK_GENERIC_SECRET),
		session.Factories.ObjectAttributeFactory.Create(CKA.CKA_VALUE,originalKey ),
		session.Factories.ObjectAttributeFactory.Create(CKA.CKA_DERIVE,true ),
	};
	var originalKeyHandler = session.CreateObject(objectAttributes);
	//creating extended key
	var mechanismParams = session.Factories.MechanismParamsFactory.CreateCkKeyDerivationStringData(dataToAddToKey);
	var mechanismType = session.Factories.MechanismFactory.Create(CKM.CKM_CONCATENATE_DATA_AND_BASE, mechanismParams);
	var extendedKeyHandler = session.DeriveKey(mechanismType, originalKeyHandler, null);
	//generating SHA1 HMAC 
	var hmacMechanism = session.Factories.MechanismFactory.Create(CKM.CKM_SHA_1_HMAC);
	var hash = session.Sign(hmacMechanism, extendedKeyHandler, data);
	//expected : 04FE079DA27D1D8A8EB812A0BCBE1D264D0A6D7C
	//result   : 31A559C06CE465831D354A3EE058A1C519180E87
}
```

**Comment by jariq** [comment]
I don't see any obvious error in your code and I'm afraid there's nothing I can do about your problem in Pkcs11Interop as it is just a .NET wrapper on top of PKCS#11 library that performs all cryptographic operations. So if you suspect that some cryptographic operation does not work as expected then you need to contact PKCS#11 library vendor and ask him for an explanation or help.
