### ISSUE TITLE
Pass private key onto a standard .Net Framework type AsymmetricAlgorithm

### ISSUE THREAD

**Issue by rabbediwi** [Pkcs11Interop/Pkcs11Interop#130]
I asked this question on Stack over flow.. i will rewrite it to limit to Pkcs11Interop
https://stackoverflow.com/questions/57324676/how-to-use-a-private-key-that-is-stored-on-an-hsm-that-is-secured-by-a-user-pass

So i am working on a use case that involves storing an non-exportable private key on a HSM.
The private key is used to authenticate with an SSH server using a 3rd party ssh library.
My code needs to authenticate with the hsm, search for the key, request the private key and pass it to a standard .Net Framework type AsymmetricAlgorithm for the 3rd party library (ssh) to make use if it.

Using the very detailed and extremely useful sample (Thank you!), I've reached this stage
```
List<IObjectHandle> foundPrivateKeys = session.FindAllObjects(privateKeyAttributes);
                if (foundPrivateKeys == null || foundPrivateKeys.Count != 1)
                    throw new Exception("Unable to find private key");

                // Use found object handles
                 privateKeyHandle = foundPrivateKeys[0];
```
Since I cant pass the private key as is since it's not exportable, how do i go about converting it or passing it on to to a standard .Net Framework type AsymmetricAlgorithm ?
appreciate your help and assistance.

**Comment by jariq** [comment]
I guess you need to implement custom class inherited from [`System.Security.Cryptography.RSA`](https://msdn.microsoft.com/en-us/library/03h9zcez(v=vs.110).aspx) class, use Pkcs11Interop in its implementation and then use an instance of your custom class as `AsymmetricAlgorithm`. You can implement it yourself or you can use [Pkcs11Interop.X509Store](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store) library which provides easy to use PKCS#11 based X.509 certificate store and contains [`Pkcs11RsaProvider`](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/0.2.0/src/Pkcs11Interop.X509Store/Pkcs11RsaProvider.cs) class inherited from `System.Security.Cryptography.RSA` class.
