### ISSUE TITLE
PublicKey of Issue!

### ISSUE THREAD

**Issue by hoatat-handsome** [Pkcs11Interop/Pkcs11Interop#133]
Hi Jim,

I am using your Pkcs11Interop library to signature a xml file
<byte[] signature = session.Sign(mechanism, privateKey, sourceData);> 

Then, I use to verify sourceDate by above signature 
<session.Verify(mechanism, publicKey, sourceData, signature, out isValid);>

But publicKey can not  the same publicKey which I used signature. So isValid always is false.
How to get publicKey which used to signature? 

Thanks,
Quang Hoa.

**Comment by jariq** [comment]
Hey @hoatat-handsome, it's hard to say what your problem is based on the information you provided. Could you please create [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that replicates your issue?

**Comment by jariq** [comment]
Closing because of 30+ days without a response.
