### ISSUE TITLE
Supporting Vendor-Specific Functions is too hard

### ISSUE THREAD

**Issue by monomosc** [Pkcs11Interop/Pkcs11Interop#137]
In order to support a single Vendor-Specific Function (replacing ```C_InitToken``` with something called ```CT_InitToken``` i would have to make (if i restrict myself to a single struct-padding/ulong-length combination)

 - a custom ```LowLevelAPIXY.Pkcs11Library``` Implementation
 - a class containing the new Method akin to ```MockDelegates```
 - a ```HighLevelAPIXY.Session``` replacement
 - a custom ```HighLevelAPI.Session```
 - Factories for LowLevelAPIXY
 - Factories for HighLevelAPIXY
 - Factories for HighLevelAPI

This seems extremely excessive, and it seems to me - though I might be wrong - that making a bunch of properties ```public``` instead of ```protected``` could solve that.

Alternatively I could break the spirit and the structure of this library and use the Helper Class ```UnmanagedLibrary``` together with ```ISession.SessionId```

Add: ~I think, making the ```Net.Pkcs11Interop.LowLevelAPI.Pkcs11Library``` in ```Net.Pkcs11Interop.HighLevelAPIXY.Session``` publicly accessible would be a good step.~ - Doesn't seem to work

**Comment by jariq** [comment]
Hello @monomosc, 

thanks for sharing your thoughts on this rather rarely discussed subject.

You might have noticed that Pkcs11Interop solution contains [Pkcs11Interop.Mock](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/5.0.0/src/Pkcs11Interop.Mock) project that demonstrates how to implement vendor specific extensions. If you look closer you will find out that I needed to manually write just `LowLevelAPI41` and `HighLevelAPI41` parts and the rest was automatically generated by `regeneratecode.sh` script that I run from [WSL](https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux) terminal. So it's less work than you originally thought and this is what I consider to be the correct way to support all platforms supported by Pkcs11Interop (currently Windows, Linux, macOS, Android and iOS). You can read more about this topic in [Pkcs11Interop library architecture](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.0.0/doc/ARCHITECTURE.md) document.

However if all you need is just a quick support for a single platform then helper class you mentioned might be a way to go.

**Comment by monomosc** [comment]
Oooooh, I didn't see the regeneratecode.sh helper script. That's the solution. Thanks  for the answer! This can be closed from my point of view.
