### ISSUE TITLE
Sample code for generating ECDSA key pair

### ISSUE THREAD

**Issue by defacto64** [Pkcs11Interop/Pkcs11Interop#138]
Hello, where can I find some example code for generating an ECDSA kay pair (say P256, for instance) ?

**Comment by jariq** [comment]
Hello @defacto64, I don't have a sample at hand but ECDSA key pair can be generated with `CKM_EC_KEY_PAIR_GEN` mechanism used with `Session.GenerateKeyPair()` method. This mechanism is described on page 219 of [PKCS#11 v2.20][0] specification. You should be able to use [`GenerateKeyPairTest` sample][1] and modify it to use `CKM_EC_KEY_PAIR_GEN` mechanism. Note that you would also need to modify attribute templates for public and private key as required by the specification.

[0]: https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf?raw=true
[1]: https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.0.0/src/Pkcs11Interop.Tests/HighLevelAPI/_18_GenerateKeyAndKeyPairTest.cs#L81

**Comment by qpernil** [comment]
You can find an example in my pkcs11-tester project here: https://github.com/qpernil/pkcs11-tester
See line 97 and on int Program.cs

You might need other attributes in the template depending on the pkcs11 library, but this works for me.

**Comment by defacto64** [comment]
Thank you, I will give it a try soon.

**Comment by qpernil** [comment]
Just checked in a bit neater examples
