### ISSUE TITLE
GetAttributeValue does not properly handle TEMPLATE attributes

### ISSUE THREAD

**Issue by dannyM42** [Pkcs11Interop/Pkcs11Interop#139]
`CKA_WRAP_TEMPLATE`, `CKA_UNWRAP_TEMPLATE` and `CKA_DERIVE_TEMPLATE` actually require 3 calls to `C_GetAttributeValue`:

1. call returns (byte) size of an `CK_ATTRIBUTE` array. Allocate it and initialize with 0.
2. call returns inside this array for **every** attribute of the `CKA_X_TEMPLATE` the needed buffer size. Allocate such a buffer for every attribute
3. call finally returns the actual values for all the attributes in the template

Please check the PKCS#11 base specification. In 3.0 draft this procedure has been clarified.

**Comment by jariq** [comment]
Hello @dannyM42 and welcome to Pkcs11Interop project!

I'll need to take a closer look at a code to confirm whether this is a bug or not. Could you please meanwhile provide more details on how did you discover the issue? Did you use Pkcs11Interop with any specific device or PKCS#11 implementation and it failed to read attribute with array of attributes?

**Comment by dannyM42** [comment]
I was investigating an issue with a 3rd party PKCS#11 library around CKA_X_TEMPLATE attributes and, therefore, had a look into the Pkcs11Interop code.
Have a look at SoftHSM2 P11Attribute implementation of retrieveAttributeMap, which is finally called by retrieve for such template attributes. This seems to be consistent with the standard.

**Comment by jariq** [comment]
Should be OK now. Thanks a lot for reporting this issue @dannyM42!
