### ISSUE TITLE
DUKPT question

### ISSUE THREAD

**Issue by onesick** [Pkcs11Interop/Pkcs11Interop#141]
Hi @jariq 
I need your expertise. I am developing pkcs11 implementatioin for DUKPT using TDES CBC encryption in Golang. Here's my PR: https://github.com/miekg/pkcs11/pull/123

However, I have trouble understanding PKCS11 and the functions.
So the BDK is CKK_DES2, and the PED sends back 10 bytes size KSN, and encrypted Data.
I use C_Derive with CKM_DES3_CBC_ENCRYPT_DATA, and send parameter CK_DES_CBC_ENCRYPT_DATA_PARAMS with IV and KSN. The PKCS11 doc says data for CK_DES_CBC_ENCRYPT_DATA_PARAMS has to be multiple of 8. So I first used 10 bytes of KSN, and padded the rest 6 bytes with either '0' or '255'. 
When I decrypt with CKM_DES3_CBC, I get some garbage value that doesn't make sense. Like this: \ufffd\u001dl\ufffdP\ufffdl\ufffd\ufffd\ufffd+\ufffd\ufffd[\ufffd\ufffdl\u0017\ufffd\ufffd\ufffd\u001f?E\ufffd[*\ufffdmd\u0014\u0009ay\ufffd\ufffd3\ufffd\ufffd

So I tried to cut the KSN to size 8 bytes either left or right, and I get back CKR_MECHANISM_PARAM_INVALID.

Can you please help me understand what I am doing wrong? I have been reading all the docs available to understand, but having a hard time.

Thanks in advance

**Comment by mcabriel** [comment]
I'm not sure if this is related and if I understood your scenario correctly, but based on my experience, you probably get those value after decrypting the data if the 1) keys/object handles used are not the same, 2) iv used in mechanism are not the same also
