### ISSUE TITLE
Update slotlist?

### ISSUE THREAD

**Issue by mythjuha** [Pkcs11Interop/Pkcs11Interop#146]
How can you detect new slots if for example a new USB smartcard reader was inserted? The GetSlotList method doesn't check for new or removed slots after it's been initialized the first time.

**Comment by jariq** [comment]
This solely depends on the implementation of your unmanaged PKCS#11 library.

Chapter 11.5 of PKCS#11 v2.20 specification states:

> All slots which `C_GetSlotList` reports must be able to be queried as valid slots by `C_GetSlotInfo`. Furthermore, the set of slots accessible through a Cryptoki library is checked at the time that `C_GetSlotList`, for list length prediction (NULL `pSlotList` argument) is called. If an application calls `C_GetSlotList` with a non-NULL `pSlotList`, and then the user adds or removes a hardware device, the changed slot list will only be visible and effective if `C_GetSlotList` is called again with `NULL`. Even if `C_GetSlotList` is successfully called this way, it may or may not be the case that the changed slot list will be successfully recognized depending on the library implementation. On some platforms, or earlier PKCS11 compliant libraries, it may be necessary to successfully call `C_Initialize` or to restart the entire system.

To sum it up, if `GetSlotList` does not work, reloading whole PKCS#11 library might help.
