### ISSUE TITLE
Safe entry from pin pad returns an error

### ISSUE THREAD

**Issue by mgebros** [Pkcs11Interop/Pkcs11Interop#147]
Hello! Thank you for your great project!

I have a simple problem: when I do Session.Login(CKU.CKU_USER, string.Empty) in order to "call" or "trigger" pinpad for pin safe entry I always get an error. If it is SPR 332 V2 device then it gets triggered, I enter the pin and then it always answers that pin is incorrect: Method C_Login returned CKR_PIN_INCORRECT. Another device which I use is OMNIKEY but when it goes to Login function it even doesnt get triggered. It directly throws an error: CKR_GENERAL_ERROR.

Same problem was with:
Session.Login(CKU.CKU_USER, "");
Session.Login(CKU.CKU_USER, null as string)
Session.Login(CKU.CKU_USER, null as byte[])
and many more...

Can you advice something please?

Thank you!

**Comment by jariq** [comment]
Well there's following statement on page 126 of [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf?raw=true):

> If the token has a "protected authentication path", as indicated by the `CKF_PROTECTED_AUTHENTICATION_PATH` flag in its `CK_TOKEN_INFO` being set, then that means that there is some way for a user to be authenticated to the token without having the application send a PIN through the Cryptoki library. One such possibility is that the user enters a PIN on a PINpad on the token itself, or on the slot device. Or the user might not even use a PIN—authentication could be achieved by some fingerprint-reading device, for example. To log into a token with a protected authentication path, the `pPin` parameter to `C_Login` should be `NULL_PTR`. When `C_Login` returns, whatever authentication method supported by the token will have been performed; a return value of `CKR_OK` means that the user was successfully authenticated, and a return value of `CKR_PIN_INCORRECT` means that the user was denied access.

Based on this information C# code utilizing protected authentication path (e.g. pinpad) should look something like this:

```csharp
ISlot slot = pkcs11Library.GetSlotList(SlotsType.WithTokenPresent).FirstOrDefault();
using (ISession session = slot.OpenSession(SessionType.ReadOnly))
{
    if (slot.GetTokenInfo().TokenFlags.ProtectedAuthenticationPath)
        session.Login(CKU.CKU_USER, (byte[]) null);
```

If this code fails, then most likely the problem is in your unmanaged PKCS#11 library and you need to ask its vendor for help.

**Comment by mgebros** [comment]
Thank you!
I just dont use "using" statements. The other things here are same.

`IPkcs11Library pkLib =  Factories.Pkcs11LibraryFactory.LoadPkcs11Library(Factories, LibraryPath, AppType.MultiThreaded);
                    
                    List<ISlot> slots = pkLib.GetSlotList(SlotsType.WithTokenPresent);

                    if (slots == null || slots.Count == 0)
                    {
                        throw new Exception("ERR_NO_READER_SLOTS_EMPTY");
                    }

                    foreach (var slot in slots.Where((x, i) => i % 2 == 1))
                    {

                        ISlot matchingSlot = slot;
                        ITokenInfo tokenInfo = null;
                        
                        try
                        {
                            tokenInfo = matchingSlot.GetTokenInfo();
                        }
                        catch (Pkcs11Exception ex)
                        {
                            if (ex.RV != CKR.CKR_TOKEN_NOT_RECOGNIZED && ex.RV != CKR.CKR_TOKEN_NOT_PRESENT)
                                throw new Exception("ERR_TOKENINFO_FAILED");
                        }
                        

                        if (matchingSlot == null)
                            throw new Exception("ERR_NO_READER_SLOTS_EMPTY");

                        ISlotInfo si = matchingSlot.GetSlotInfo();
                        
                        var session = matchingSlot.OpenSession(SessionType.ReadOnly);                        

                        var signatureToken = new CardSignatureToken(session);
                            if (!signatureToken.IsValidToken())
                                throw new Exception("ERR_SIGNATURE_TOKEN_INVALID");

                        var padInfo = new CardReaderInfo(si);
                        
                        if (padInfo.HasPinpad)
                        {
                            session.Login(CKU.CKU_USER, null as byte[]);`

**Comment by mgebros** [comment]
Just teste it with Pkcs11Admin. Results and error names were absolutely same. Usual login worked from keyboard. However, protected login gave erros like this:
![image](https://user-images.githubusercontent.com/47592547/76435031-ee8fc100-63cf-11ea-9358-226c461e3936.png)

**Comment by jariq** [comment]
OK, test with Pkcs11Admin confirms that you need to troubleshoot this error with a producer of unmanaged PKCS#11 library `pkcs11-geo-eid-x64.dll`.
