### ISSUE TITLE
GetSlotList invalid slots quantity

### ISSUE THREAD

**Issue by mgebros** [Pkcs11Interop/Pkcs11Interop#148]
As was recommended I am using only 1 instance of pkcs11 lib class. If connected id card reader device/devices are untouched GetSlotList() function return the correct slots. However if I plug out and plug in devices it gets messed out. Sometimes it shows more slots sometimes less. 

At the beginning I thought it was the problem with PCSC Monitoring class. I have 2 classes there: one monitors the connected readers and second monitors the cards inside them.  However after debugging as I found out it was the problem with GetSlotList() function.

**Comment by mgebros** [comment]
Is there any way to clear or refresh the "saved usb slots" inside  Pkcs11 class?
Or should I delete/dispose the Pkcs11 class after each use?

**Comment by jariq** [comment]
Pkcs11Interop does not cache anything. Refresh of slots depends solely on the implementation of your unmanaged PKCS#11 library. `IPkcs11Library::GetSlotList()` does nothing else but returns slots provided by `C_GetSlotList` function of unmanaged PKCS#11 library.

If `IPkcs11Library::GetSlotList()` does not work then your best bet is to reload whole PKCS#11 library or contact unmanaged library vendor.

Similar issue: #146
