### ISSUE TITLE
Is it possible to talk to the Windows CSP via PKCS11 too?

### ISSUE THREAD

**Issue by drauch** [Pkcs11Interop/Pkcs11Interop#151]
Is it possible to generically use a PKCS#11 library like yours and switch between using keys from an underlying HSM and keys from the Windows CSP? Do you know of a library doing so?

Best regards,
D.R.

**Comment by jariq** [comment]
There's quite a few options actually:

- https://github.com/PeculiarVentures/pvpkcs11
- https://github.com/risacher/p11-capi
- `c:\Program Files\Mozilla Firefox\osclientcerts.dll`

**Comment by drauch** [comment]
Oh nice, thanks for the quick reply! I'll give them a try.
