### ISSUE TITLE
Relevant commands of APDU

### ISSUE THREAD

**Issue by mgebros** [Pkcs11Interop/Pkcs11Interop#153]
Do we have any table or list where can I see which APDU commands are used by functions of your pkcs11 library?

I still have problem with safe PIN entry, so I want to call same C_Login function on the level of APDU if possible.

Thank you!

**Comment by jariq** [comment]
Pkcs11Interop does not emit/send/use any APDU commands. It just calls functions exposed by your unamanaged PKCS#11 library (library provided by device vendor).
