### ISSUE TITLE
Example reading a certificate with a Token

### ISSUE THREAD

**Issue by billib0bs** [Pkcs11Interop/Pkcs11Interop#154]
Good afternoon. You can show an example of reading certificate information with eToken. To whom it was issued, the certificate validity period.

**Comment by jariq** [comment]
Hello,

it is highly recommended that before you start using Pkcs11Interop you get familiar at least with *"Chapter 2 - Scope"*, *"Chapter 6 - General overview"* and *"Chapter 10 - Objects"* of [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf?raw=true) (or equivalent chapters of any previous or subsequent specification version).

Then you can proceed and examine following code samples:
- [HighLevelAPI/_17_ObjectFindingTest.cs](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.0/src/Pkcs11Interop.Tests/HighLevelAPI/_17_ObjectFindingTest.cs)
- [HighLevelAPI/_16_GetAndSetAttributeValueTest](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.0/src/Pkcs11Interop.Tests/HighLevelAPI/_16_GetAndSetAttributeValueTest.cs)

You'll need to find certificate objects, read `CKA_VALUE` attribute of each of them and parse it with `X509Certificate2` class.

As an alternative you may take a look at [Pkcs11Interop.X509Store](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store) which provides simpler interface.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
