### ISSUE TITLE
Pkcs11 Interop : Exception Method C_Sign Returned 2147483768

### ISSUE THREAD

**Issue by AbhishekPandey16** [Pkcs11Interop/Pkcs11Interop#156]
I am using Pkcs11 Interop sign method to sign my byte content. I am able to sign a small amount of data 1 kb but it fails with more than 2 kb it fails with exception Method C_Sign Returned 2147483768. I am using the code sample below

// Find first slot with token present
            ISlot slot = Helpers.GetUsableSlot(pkcs11Library);

            // Open RW session
            using (ISession session = slot.OpenSession(SessionType.ReadWrite))
            {
                // Login as normal user
                session.Login(CKU.CKU_USER, {user partition password});

                IObjectHandle privateKey = able to fetch the key with my code;

                // Specify signing mechanism
                IMechanism mechanism = session.Factories.MechanismFactory.Create(CKM.CKM_SHA1_RSA_PKCS);

                byte[] sourceData = ConvertUtils.Utf8StringToBytes("converted string from a file more than 2 kb");

                // Sign data
                byte[] signature = session.Sign(mechanism, privateKey, sourceData);
}

Can someone please help here.

**Comment by jariq** [comment]
`C_Sign` method returned decimal value `2147483768` which is `0x‭80000078‬` hexadecimal. All return values that start with `0x8` are vendor specific values and as such are not explained in PKCS#11 specification. You'll need to discuss your issue with the vendor of your device / PKCS#11 library.
