### ISSUE TITLE
Comparing KEY_TYPE attributes

### ISSUE THREAD

**Issue by diegonc** [Pkcs11Interop/Pkcs11Interop#167]
Hello, I'm trying to compare the key type of a private key with code as below

```c#
/* Retrieve key type*/
List<IObjectAttribute> _keyType = session.GetAttributeValue(privateKeys[0], new List<CKA> { CKA.CKA_KEY_TYPE });
IObjectAttribute keyType = _keyType[0];

/* Check for RSA key */
var RSA = factories.ObjectAttributeFactory.Create(CKA.CKA_KEY_TYPE, CKK.CKK_RSA);
if (keyType.Equals(RSA))
{
  /* ... do something */
}
```

However this does not seem to work as the if condition is not met.
On the other side, using the code below, _apparently_, does work:

```c#
if (keyType.GetValueAsUlong() == (ulong) CKK.CKK_RSA)
{
  /* ... do something */
}
```
CKK_RSA is 0 and keyType.GetValueAsUlong() returns 0.

Is the first approach meant to work? Is the latter working by chance?

**Comment by jariq** [comment]
The second approach is correct.

**Comment by diegonc** [comment]
Thank you! I'll close this issue now.
