### ISSUE TITLE
Unable login using CKU_CONTEXT_SPECIFIC, Always getting CKR_USER_TYPE_INVALID

### ISSUE THREAD

**Issue by alimerdan** [Pkcs11Interop/Pkcs11Interop#169]
I'm trying to connect to a Thales DPOD HSM using Pkcs11Interop library (using C# .net Core 2.1)
I'm able to login using CKU_USER or CKU_SO with their corresponding pin codes,
but when trying to login using CKU_CONTEXT_SPECIFIC i always get an error 
> "Method C_Login returned CKR_USER_TYPE_INVALID"

I'm able to login normally using a provided CLI client: 
![image](https://user-images.githubusercontent.com/5233636/99465073-3644f000-2942-11eb-8ee6-9e8a7e25f6e6.png)
where the assumed mapping should be:
Partition SO -> CKU_SO,
Crypto Officer -> CKU_USER,
Crypto User -> CKU_CONTEXT_SPECIFIC

I was not able to find any code samples/tests that using CKU_CONTEXT_SPECIFIC user logins
here is the code that I'm using:

```
public static ISession ConnectToHSM(out ISlot slot, SessionType sessionType = SessionType.ReadOnly)
        {
            try
            {
                // Create factories used by Pkcs11Interop library
                Pkcs11InteropFactories factories = new Pkcs11InteropFactories();

                // Load unmanaged PKCS#11 library
                IPkcs11Library pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, Options.PKCS11LibraryPath(), AppType.SingleThreaded);

                // Find first slot with token present
                slot = pkcs11Library.GetSlotList(SlotsType.WithTokenPresent)[0];

                // Open RW session
                ISession session = slot.OpenSession(sessionType);

                // Login as normal user -> Does not work in case of CKU_CONTEXT_SPECIFIC
                session.Login(CKU.CKU_CONTEXT_SPECIFIC,Options.Pin_CU());
                //session.Login(CKU.CKU_USER, Options.Pin_CO()); -> This one works
                //session.Login(CKU.CKU_SO, Options.Pin_SO()); -> This one works
                return session;
            }
            catch (Exception ex)
            {
                throw new Exception("Failed to Connect to HSM, with the following details '" + ex.Message + "'", ex);
            }
        }
```
Not sure if i missed something or it is an issue that needs to be solved in the library itself.

Please Advise!

**Comment by qpernil** [comment]
As far as I understand the pkcs#11 spec the context specific user type can only be used after a C_SignInit, C_VerifyInit, C_EncryptInit or C_DecryptInit have been called and before those operations have been concluded. The intent is for it to be used to login again for token keys that require an additional PIN verification each time they are used. As the above mentioned functions can only typically be called after C_Login it usually follows that you must also already be logged in as USER or SO.

**Comment by alimerdan** [comment]
Thanks @qpernil for your comment,
I've tried what you already mentioned with LowLevelAPI41,
but unfortunately,
Same results

> "Method C_Login returned CKR_USER_TYPE_INVALID"

I also cannot find useful examples online for a sample code that was able to login using CKU_CONTEXT_SPECIFIC.

Please Advise!

**Comment by jariq** [comment]
@alimerdan you are assuming that `Crypto User` maps to `CKU_CONTEXT_SPECIFIC` but `CKR_USER_TYPE_INVALID` error might indicate that your assumption is not correct. You should contact Thales support and ask them whether your assumption is correct.

**Comment by qpernil** [comment]
So with ykcs11 you could do this :
C_OpenSession(..)
C_Login(CKU_USER, ...)
...
Something else that accesses the device...
...
C_SignInit(...)
C_Login(CKU_CONTEXT_SPECIFIC, ...)
C_SIgnUpdate(... )
C_SignFinal(...)

That last C_Login would be needed to verify the PIN if they key used requires PIN to be verified just before the Sign operation, every time, and something has 'used up' the first PIN verification (including an earlier sign operation)

Since Pkcs11Interop's high level API combines the SignInit, SignUpdate, SignFinal operations (I think) you can't do this sequence using that API. 

BR
Per

**Comment by qpernil** [comment]
In fact I would wish that the separated functions existed in the high level API to enable this use case without resorting to the low-level api. I might be missing something, please let me know if that's the case.

**Comment by qpernil** [comment]
@alimerdan my point was that C_Login(CKU_CONTEXT_SPECIFIC,... ) *should* not work as used in your example according to how I understand the spec. I don't know how your particular pkcs#11 library actually works of course.

**Comment by jariq** [comment]
> In fact I would wish that the separated functions existed in the high level API to enable this use case without resorting to the low-level api. I might be missing something, please let me know if that's the case.

@qpernil two new overloads `Session::Sign(IMechanism mechanism, IObjectHandle keyHandle, byte[] keyPin, byte[] data)` and `Session::Sign(IMechanism mechanism, IObjectHandle keyHandle, string keyPin, byte[] data)` were introduced into `HighLevelAPI` in Pkcs11Interop 5.0 as a part of https://github.com/Pkcs11Interop/Pkcs11Interop/issues/71 to handle the scenario you described 😉 

Anyway I still believe @alimerdan is looking for some vendor defined `CKU` constant and needs to contact Thales support to get its value. Or maybe it can be found in their documentation. 🤷‍♂️

**Comment by qpernil** [comment]
@jariq Excellent ! I had missed that :-)

**Comment by alimerdan** [comment]
Thank you all lot for your support and ideas,

as @jariq said, the assumption that `CKU_CONTEXT_SPECIFIC` is mapped to the `Crypto User` role was not correct,

I've found that the Crypto User ID for Thales cryptoki.dll is 2147483649 - while requesting to Initialize Pin using ckdemo.exe
![image](https://user-images.githubusercontent.com/5233636/99715889-159aa880-2ab0-11eb-910b-f592f4eca273.png)

Accordingly I've changed my login function to:

`session.Login((CKU)2147483649, Options.Pin_CU());`

and It worked successfully 🥇
