### ISSUE TITLE
Questions about using Pkcs11Interop or Pkcs11Interop.X509Store

### ISSUE THREAD

**Issue by Weiderson** [Pkcs11Interop/Pkcs11Interop#181]
Can I use some of these libraries (Pkcs11Interop or Pkcs11Interop.X509Store) to read the cryptographic tokens private key to generate signed files in CMS/CADES format in a mvc client web application? _Each client signing a document will have their own personal token. I plan to use it with Bouncy Castle._

**Comment by jariq** [comment]
Pkcs11Interop as a part of MVC application running on server can access only tokens connected to server. If you want to access tokens connected to client machine with Pkcs11Interop then you need to have some .NET application running on client machine.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
