### ISSUE TITLE
Building Pkcs11Interop on Linux with Net 2.0, Net 4.0, Net 4.5 frameworks

### ISSUE THREAD

**Issue by lo1ol** [Pkcs11Interop/Pkcs11Interop#183]
Hello!

Recently I've tried to build Pkcs11Interop nuget package on Linux (Ubuntu 20.04) and noticed this lines
https://github.com/Pkcs11Interop/Pkcs11Interop/blob/cf5508e3e81b7fe73bc9a6e7f1d0bd7b5ea44c3d/src/Pkcs11Interop/Pkcs11Interop.csproj#L3-L9

Is there any reason not to build nuget package with versions for Net 2.0, Net 4.0, Net 4.5 frameworks on Linux machine? Removing this conditions doesn't break building on my linux machine.

**Comment by jariq** [comment]
There's no particular reason for it. I just didn't think it's possible to build anything other on a Linux machine.

**Comment by lo1ol** [comment]
Thanks. we are trying to automate builing and publishing our nuget package. We are wanted to do it an linux machine, but there is some problems with signing.

Nevererless, thank you!
