### ISSUE TITLE
CSR generation

### ISSUE THREAD

**Issue by Dvergatal** [Pkcs11Interop/Pkcs11Interop#187]
Hi all,
is it possible to generate CSR from key pair on the token using only Pkcs11Interop api or do i need to write my own code?

BR
Piotr

**Comment by jariq** [comment]
Standard PKCS#11 API does not provide any functions for creation of CSRs.
You can use Pkcs11Interop with [BouncyCastle](https://www.nuget.org/packages/Portable.BouncyCastle/) library the same way [Pkcs11Admin](https://pkcs11admin.net/) does:
https://github.com/Pkcs11Admin/Pkcs11Admin/blob/0.5.0/src/Pkcs11Admin/Pkcs11Slot.cs#L1066-L1078
