### ISSUE TITLE
Processing is failed after CKR Error is faced.

### ISSUE THREAD

**Issue by MetaphorSimilies** [Pkcs11Interop/Pkcs11Interop#188]
Please find the below details : 

1. We have a windows application written in C# .Net which is responsible for file encryption/decryption, it uses HSM card for PKI Operation and and Pkc11Interop has a wrapper.
2. During processing we have faced CKR_DEVICE_ERROR and then after no file were getting process (i.e. encryption/decryption).
3. File started processing only after windows application service was restarted.

Please find the below CKR_DEVICE_ERROR  error log:
_"Error Code CKR_DEVICE_ERROR and Stack Trace    at Net.Pkcs11Interop.HighLevelAPI41.Session.Decrypt(Mechanism mechanism, ObjectHandle keyHandle, Stream inputStream, Stream outputStream, Int32 bufferLength)"_

Please find the below error log which we were facing for which we need to do application service restart:
_"Error Code 2147483674 and Stack Trace    at Net.Pkcs11Interop.HighLevelAPI41.Session.UnwrapKey(Mechanism mechanism, ObjectHandle unwrappingKeyHandle, Byte[] wrappedKey, List`1 attributes)
   at Net.Pkcs11Interop.HighLevelAPI.Session.UnwrapKey(Mechanism mechanism, ObjectHandle unwrappingKeyHandle, Byte[] wrappedKey, List`1 attributes)"_

Please help to find the below concern:
1. Why processing didn't resume once HSM card was up again and windows application service restart was required.

Thanks for Help.

**Comment by jariq** [comment]
Error code `2147483674` dec is `0x8000001` hex which means it is vendor defined error code => you need to contact HSM vendor support.
