### ISSUE TITLE
build library on .net standard 2.1

### ISSUE THREAD

**Issue by jiten87** [Pkcs11Interop/Pkcs11Interop#189]
is it fine to upgrade the .net standard version to 2.1. I am upgrading the .net standard version because I don't have to support .netcore 2.0 since my app's minimum support .netcore is 3.1.

**Comment by jariq** [comment]
IMO you should be able to use .NET Standard 2.0 library in .NET Core 3.1 application without any problems.  
Are you experiencing any specific problems?

**Comment by jiten87** [comment]
Right, But the minimum version that I have to support for my application is .NET Core 3.1. And I also don't have to provide .Net framework support. That's thinking about upgrade the interop library version to .Net Standard 2.1.

**Comment by jariq** [comment]
.NET Standard version limits the lowest/oldest version of runtime you can use not the highest/newest version of runtime. There's currently no benefit in just rebuilding Pkcs11Interop for `netstandard21`. Even [official Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target) states that libraries should target lowest version possible:

> We recommend you target the lowest version of .NET Standard possible.

However Pkcs11Interop is open-source and you can rebuild it any way you like if it's in line with its license. But why would you waste your time rebuilding it with no clear benefit when you can use already available nuget package in just 10 seconds? 🤷🏻‍♂️

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
