### ISSUE TITLE
Possible to generate a new key pair for an already existing certificate?

### ISSUE THREAD

**Issue by manar-shawkey** [Pkcs11Interop/Pkcs11Interop#190]
I have mistakenly called DesyroyObject() on a public and private key pair of a specific certificate. Is there any way to retrieve the keys? or if I have the thumbprint of the certificate is it possible to generate a pair for it? 
The token I am using is epass2003. When I open the certificate details from the PKI manager, I can see the public key. However, when I try to search it I get no public key objects at all. The search method I am using is: 

```
private IObjectHandle getPublicKey(ISession session)
        {
            List<IObjectAttribute> objectAttributes = new List<IObjectAttribute>();
            objectAttributes.Add(session.Factories.ObjectAttributeFactory.Create(CKA.CKA_CLASS, CKO.CKO_PUBLIC_KEY));
            List<IObjectHandle> foundObjects = session.FindAllObjects(objectAttributes);
            Console.WriteLine(foundObjects.Count);
            Assert.IsTrue(foundObjects.Count > 0);
            return foundObjects[0];
        }

```

**Comment by jariq** [comment]
Public key value is present in certificate so you can use it to restore public key object. However private key is lost forever.

**Comment by manar-shawkey** [comment]
Thank you sir for the fast reply :)
