### ISSUE TITLE
How to directly store a generated random number into a data object?

### ISSUE THREAD

**Issue by RufusJWB** [Pkcs11Interop/Pkcs11Interop#196]
I would like to generate a random number on an HSM and wrap it there with an RSA public key. Currently I do the following:

```
// random data
Console.WriteLine("Create plaintext secret");
byte[] randomData = session.GenerateRandom(32);
 
// create DATA ...
// Prepare attribute template of new data object
List<IObjectAttribute> plaintextSecretObjectAttributes = new List<IObjectAttribute>();
plaintextSecretObjectAttributes.Add(session.Factories.ObjectAttributeFactory.Create(CKA.CKA_CLASS, CKO.CKO_DATA));
plaintextSecretObjectAttributes.Add(session.Factories.ObjectAttributeFactory.Create(CKA.CKA_TOKEN, true));
plaintextSecretObjectAttributes.Add(session.Factories.ObjectAttributeFactory.Create(CKA.CKA_LABEL, "Plaintext Secret Salesforce " + options.keyLabel));
plaintextSecretObjectAttributes.Add(session.Factories.ObjectAttributeFactory.Create(CKA.CKA_VALUE, randomData));
// Create object
IObjectHandle plaintextSecretObjectHandle = session.CreateObject(plaintextSecretObjectAttributes);
Console.WriteLine("plaintext secret stored in HSM");

// Do the wrapping

```

Now my problem is that the randomData leaves the HSM and gets uploaded into it again. I would like to skip this and store the randomData directly into a data object in the HSM without having it in the memory of the computer. Is there a way to do this?

**Comment by jariq** [comment]
All right. Let's suppose you would be able to rewrite that script with `CKK_GENERIC_SECRET` key and RSA key wrapping. This would allow you to generate secret and transfer it to salesforce without exposing the secret into the host memory. But what then? How do you plan to use that secret in a real world operations performed later?

**Comment by RufusJWB** [comment]
> In some cases generating the symmetric key of `CKK_GENERIC_SECRET` type is a feasible alternative to `session.GenerateRandom` followed by importing the value into HSM. Maybe it could work for you too?

I can confirm it is working. Thank you for your support. I'll close this ticket.
