### ISSUE TITLE
AES CMAC Support

### ISSUE THREAD

**Issue by MostafaRamadan1** [Pkcs11Interop/Pkcs11Interop#197]
Hello, 
I am trying to generate Aes Cmac based on a stored key on HSM, here is my logic 

```
        public byte[] GenerateCmac(byte[] data, byte[] iv)
        {
            // Helper to get the session, works fine
            var session = pKCS11Connector.GetSession(SessionType.ReadWrite);
            // Helper function to get existing Aes key, works fine
            IObjectHandle obj = GetObj(session, "AesKey");
            var mechanism = session.Factories.MechanismFactory.Create(CKM.CKM_AES_CMAC, iv);
            return session.Sign(mechanism, obj, data);
        }
```
But I always get exception:  Net.Pkcs11Interop.Common.Pkcs11Exception Method C_SignInit returned CKR_MECHANISM_PARAM_INVALID
 
Any idea or example to follow on how to generation CMAC

**Comment by jariq** [comment]
Chapter 2.13.2 of [PKCS#11 v2.40](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.40/pkcs11-curr-v2.40-errata01-os-complete.pdf?raw=true) states:

> CKM_AES_CMAC does not use a mechanism parameter.

**Comment by MostafaRamadan1** [comment]
Thanks Jariq, for the support, I ended up using mechanism without mechanism parameters
`var mechanism = session.Factories.MechanismFactory.Create(CKM.CKM_AES_CMAC); `
like you mentioned, but also to note here, I update the key attributes on HSM to accept sign and verify operation(this just a note if somebody facing this!)
