### ISSUE TITLE
Can I connect to HSM using .net core API by PKCS11

### ISSUE THREAD

**Issue by sanjeevkumar0589** [Pkcs11Interop/Pkcs11Interop#200]

**Comment by jariq** [comment]
If your HSM comes with PKCS#11 library/driver then you should be able to use it via Pkcs11Interop from .NET Core.

**Comment by jariq** [comment]
That's out of scope for Pkcs11Interop project. Please contact HSM vendor support.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
