### ISSUE TITLE
Get a new slot connection

### ISSUE THREAD

**Issue by AndreArantes** [Pkcs11Interop/Pkcs11Interop#201]
Hi,

I'm trying to use the WaitForSlotEvent function, so after a insert token event I could get the slot ID, but I cant find a way to create a new slot from that. Also when I try to list the slots again I only get the old listed slots, I mean the slots that are already connected when the PKCS11 library was load. Can you help me and tell me if there are a method to do that?

In my case my application is already running and I'm trying to get new token connections.

Thank for your attention.

Regards, 
Andre Arantes.

**Comment by jariq** [comment]
Slot represents logical reader (e.g. smartcard reader) that potentially contains a token (e.g. smartcard).

`C_WaitForSlotEvent` waits for a slot event, such as **token insertion** or **token removal**, to occur. In my understanding, only slots previously detected and returned by a call to `C_GetSlotList` are be monitored for such events.

`C_WaitForSlotEvent` returns `slotId` which helps you identify the slot in the list previously acquired by calling `C_GetSlotList`. This identification can be performed by comparing `slotId` with `ISlot::SlotId`. So you don't need to create new slot, you just need to find it in the list of already present slots.

If you are connecting/adding whole new slot and it does not show up in the list returned by `GetSlotList` then IMO you need to reload whole PKCS#11 library (dispose `IPkcs11Library` and load it again). [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf?raw=true) states that this behavior is implementation dependent and sometimes you might even need to restart OS to detect a connection of the new slot:

> Even if `C_GetSlotList` is successfully called this way, it may or may not be the case that the
> changed slot list will be successfully recognized depending on the library
> implementation. On some platforms, or earlier PKCS11 compliant libraries, it may be
> necessary to successfully call `C_Initialize` or to restart the entire system.

**Comment by AndreArantes** [comment]
I understand, maybe I must try to list all slots instead of only the token present ones. Then when an event occurred in a slot I will try to find it by the slot ID, I think that is the idea, right?

So that way I dont need to restart the application or system, and affect the other slots in process. Because that is the main problema here.

**Comment by AndreArantes** [comment]
Finally it works, I used the event function to get the slot ID then I search for it in the slots list. 

Thank you for your attention @jariq.
