### ISSUE TITLE
This certificate has an invalid digital signature.

### ISSUE THREAD

**Issue by kumarsanjeev0589** [Pkcs11Interop/Pkcs11Interop#202]
I am doing sign certificate using PKSCS#11 but getting error on certificate details tab after install also.

Generate Signature : - 

byte[] signature = null;
            IMechanism mechanism = this.Session.Factories.MechanismFactory.Create(CKM.CKM_SHA256_RSA_PKCS);
            private HashAlgorithmName[] _hashNamesPkcs1 = new HashAlgorithmName[] {HashAlgorithmName.SHA256};
            foreach (HashAlgorithmName hashAlgName in _hashNamesPkcs1)
            {
                byte[] hash = ComputeHash(this._input, hashAlgName);                
                byte[] pkcs1DigestInfo = CreatePkcs1DigestInfo(hash, hashAlgName);
                if (pkcs1DigestInfo == null)
                    throw new NotSupportedException(string.Format("Algorithm {0} is not supported", hashAlgName.Name));

                signature = this.Session.Sign(mechanism, this._keyHandle, pkcs1DigestInfo);
            }

I am using ncipher HSM.

Custom Signature class
internal class CustomRsaDigestSigner : ISigner
    {
        private readonly IObjectHandle _keyHandle;
        private byte[] _input;

        private ISession Session;
        private byte[] randomNumber;
        public readonly HSMConfig hSMConfig;
        public readonly IHSMHelpers hSMHelpers;

        private HashAlgorithmName[] _hashNamesPkcs1 = new HashAlgorithmName[] {HashAlgorithmName.SHA256};

        public CustomRsaDigestSigner(IObjectHandle keyHandle, HSMConfig hSMConfig, IHSMHelpers hSMHelpers, ISession session, byte[] randomNumber)
        {
            this._keyHandle = keyHandle;
            this.hSMConfig = hSMConfig;
            this.hSMHelpers = hSMHelpers;
            this.Session = session;
            this.randomNumber = randomNumber;
        }

        public void Init(bool forSigning, ICipherParameters parameters)
        {
            this.Reset();
        }

        public void Update(byte input)
        {
            throw new NotImplementedException();
        }

        public void BlockUpdate(byte[] input, int inOff, int length)
        {
            this._input = input.Skip(inOff).Take(length).ToArray();
        }

        public byte[] GenerateSignature()
        {
            byte[] signature = null;
            IMechanism mechanism = this.Session.Factories.MechanismFactory.Create(CKM.CKM_SHA256_RSA_PKCS);

            foreach (HashAlgorithmName hashAlgName in _hashNamesPkcs1)
            {
                byte[] hash = ComputeHash(this._input, hashAlgName);                
                byte[] pkcs1DigestInfo = CreatePkcs1DigestInfo(hash, hashAlgName);
                if (pkcs1DigestInfo == null)
                    throw new NotSupportedException(string.Format("Algorithm {0} is not supported", hashAlgName.Name));

                signature = this.Session.Sign(mechanism, this._keyHandle, pkcs1DigestInfo);
            }
            return signature;
        }

        public void Reset() { }

        public bool VerifySignature(byte[] signature)
        {
            bool isValid;
            IMechanism mechanism = this.Session.Factories.MechanismFactory.Create(CKM.CKM_SHA256_RSA_PKCS);
            using (MemoryStream inputStream = new MemoryStream(this._input))
            {
                // Verify signature
                var test = Convert.ToBase64String(signature);
                this.Session.Verify(mechanism, this._keyHandle, inputStream, signature, out isValid, 4096);
            }
            return isValid;
        }

        public static byte[] ComputeHash(byte[] data, HashAlgorithmName hashAlgName)
        {
            using (System.Security.Cryptography.HashAlgorithm hashAlg = System.Security.Cryptography.HashAlgorithm.Create(hashAlgName.Name))
                return hashAlg.ComputeHash(data);
        }

        private static byte[] CreatePkcs1DigestInfo(byte[] hash, HashAlgorithmName hashAlgorithm)
        {
            if (hash == null || hash.Length == 0)
                throw new ArgumentNullException(nameof(hash));

            byte[] pkcs1DigestInfo = null;

            if (hashAlgorithm == HashAlgorithmName.MD5)
            {
                if (hash.Length != 16)
                    throw new ArgumentException("Invalid lenght of hash value");

                pkcs1DigestInfo = new byte[] { 0x30, 0x20, 0x30, 0x0C, 0x06, 0x08, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x02, 0x05, 0x05, 0x00, 0x04, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                Array.Copy(hash, 0, pkcs1DigestInfo, pkcs1DigestInfo.Length - hash.Length, hash.Length);
            }
            else if (hashAlgorithm == HashAlgorithmName.SHA1)
            {
                if (hash.Length != 20)
                    throw new ArgumentException("Invalid lenght of hash value");

                pkcs1DigestInfo = new byte[] { 0x30, 0x21, 0x30, 0x09, 0x06, 0x05, 0x2B, 0x0E, 0x03, 0x02, 0x1A, 0x05, 0x00, 0x04, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                Array.Copy(hash, 0, pkcs1DigestInfo, pkcs1DigestInfo.Length - hash.Length, hash.Length);
            }
            else if (hashAlgorithm == HashAlgorithmName.SHA256)
            {
                if (hash.Length != 32)
                    throw new ArgumentException("Invalid lenght of hash value");

                pkcs1DigestInfo = new byte[] { 0x30, 0x31, 0x30, 0x0D, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01, 0x05, 0x00, 0x04, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                Array.Copy(hash, 0, pkcs1DigestInfo, pkcs1DigestInfo.Length - hash.Length, hash.Length);
            }
            else if (hashAlgorithm == HashAlgorithmName.SHA384)
            {
                if (hash.Length != 48)
                    throw new ArgumentException("Invalid lenght of hash value");

                pkcs1DigestInfo = new byte[] { 0x30, 0x41, 0x30, 0x0D, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x02, 0x05, 0x00, 0x04, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                Array.Copy(hash, 0, pkcs1DigestInfo, pkcs1DigestInfo.Length - hash.Length, hash.Length);
            }
            else if (hashAlgorithm == HashAlgorithmName.SHA512)
            {
                if (hash.Length != 64)
                    throw new ArgumentException("Invalid lenght of hash value");

                pkcs1DigestInfo = new byte[] { 0x30, 0x51, 0x30, 0x0D, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x03, 0x05, 0x00, 0x04, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
                Array.Copy(hash, 0, pkcs1DigestInfo, pkcs1DigestInfo.Length - hash.Length, hash.Length);
            }

            return pkcs1DigestInfo;
        }

        public string AlgorithmName => "SHA-256withRSA";
    }

**Comment by jariq** [comment]
Looks like you're hashing the input twice. First time in `ComputeHash` method and then again in `CKM_SHA256_RSA_PKCS`.

**Comment by kumarsanjeev0589** [comment]
I am creating certificate using Bouncycastle API and read public key from HSM and generate signature using PrivateKey object ID , , TbsCertificate.GetEncoded() and Mechanism
IMechanism mechanism = this.Session.Factories.MechanismFactory.Create(CKM.CKM_SHA256_RSA_PKCS);

**Comment by jariq** [comment]
Closing because of 14+ days without an activity.
