### ISSUE TITLE
ISlot.GetTokenInfo return CKR_GENERAL_ERROR on OSX (libproidqcm11.dylib)

### ISSUE THREAD

**Issue by ficnar** [Pkcs11Interop/Pkcs11Interop#204]
On the system OSX 12 Monterey .NET Core 3.1 application with ProID+Q token raise exception:

```
Net.Pkcs11Interop.Common.Pkcs11Exception: Method C_GetTokenInfo returned CKR_GENERAL_ERROR
   at Net.Pkcs11Interop.HighLevelAPI80.Slot.GetTokenInfo()
```

PKCS11 installed from original manufacturer download:
https://proid.cz/ke-stazeni/#1610979102811-feeb9a1b-4b20

The same token and PKCS11 library on OSX in FireFox work properly.
The same token in the same .NET Core 3.1 application on Windows with proidqcm11.dll works properly.
Only OSX with Pkcs11Interop raise an exception.

**Comment by jariq** [comment]
Function `C_GetTokenInfo` is exported by `libproidqcm11.dylib` library and when it returns `CKR_GENERAL_ERROR` there is nothing Pkcs11Interop can do about it. You need to contact device vendor support. Vendor support will most likely tell you how to collect logs from their library, they will analyze the logs and tell you the reason why `C_GetTokenInfo` returns `CKR_GENERAL_ERROR`.
