### ISSUE TITLE
Linking fails on dotnet6.0-macos with universal dylib

### ISSUE THREAD

**Issue by mmoraga** [Pkcs11Interop/Pkcs11Interop#206]
I don't know if this is an issue with dotnet6.0-macos or Pkcs11Interop, but trying to build an app with Pkcs11Interop + empty-pkc11 fails with:
``` 
Tool xcrun execution finished (exit code = 1).

  ld: library not found for -lempty-pkcs11-universal
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I instead try linking with Content Include instead of NativeReference
```
    <Content Include="..\..\Lib\empty-pkcs11-universal.dylib">
      <Link>empty-pkcs11-universal.dylib</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
```
the linking succeeds if building only for x64, but trying to build for arm64 fails due to missing symbols (Same issue as when building for macos without including the empty-pkcs11 lib). I have modified the empty-pkcs11 library to build a fat binary for both arm64 x86_64, and symbols should be there when checking with `nm -a`

csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0-macos</TargetFramework>
        <RootNamespace>dotnet_macos_cert</RootNamespace>
        <ApplicationId>com.example.app</ApplicationId>
        <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
        <SelfContained>true</SelfContained>
        <Nullable>enable</Nullable>
        <SupportedOSPlatformVersion>10.15</SupportedOSPlatformVersion>
    	<MtouchExtraArgs>-v -v -v -v</MtouchExtraArgs>
    </PropertyGroup>
    <ItemGroup>
	<Content Include="empty-pkcs11-universal.dylib">
      		<Link>empty-pkcs11-universal.dylib</Link>
        	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
  	</Content>
        <NativeReference Include="empty-pkcs11-universal.dylib">
            <Kind>Dynamic</Kind>
            <SmartLink>False</SmartLink>
        </NativeReference>
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Pkcs11Interop" Version="5.1.2" />
    </ItemGroup>

</Project>
```

**Comment by jariq** [comment]
This is an expected behavior of Pkcs11Interop used with Xamarin.Mac. See https://github.com/Pkcs11Interop/Pkcs11Interop/issues/109#issuecomment-460057860 for an explanation.

**Comment by mmoraga** [comment]
I think you misunderstood me, I was using the empty-pkcs-11 as described in that issue, and it was working before with Xamarin.mac. The issue turned out to be with `dotnet6.0-mac` and can be fixed by renaming the empty pkcs library to `libempty-pkcs11-x64`, see: https://github.com/xamarin/xamarin-macios/issues/15044

I will probably open a PR in https://github.com/Pkcs11Interop/empty-pkcs11 to fix the name and also add arm64/universal support if it's fine by you.

**Comment by jariq** [comment]
Sure go ahead but please create separate PR for each of the changes.
