### ISSUE TITLE
Cryptographic module for Android and iOS

### ISSUE THREAD

**Issue by pgrapso** [Pkcs11Interop/Pkcs11Interop#207]
Hello,

we are trying to use you library for a mobile app but we still struggling with find the proper Cryptographic modules for android and iOS. Do you have any suggestions? In your sample this have been mocked and for iOS you set a string.empty.

Thanks and regards

**Comment by jariq** [comment]
I'm not aware of any vendor providing PKCS#11 library for Android or iOS.

**Comment by pgrapso** [comment]
> I'm not aware of any vendor providing PKCS#11 library for Android or iOS.

Hey Jariq,

thanks a lot for your quick reply...appreciate it.

I was looking at your repo and found this: https://github.com/Pkcs11Interop/empty-pkcs11#android. Is it something we can use and even on a production app? If you are not aware of any vendor providing PKCS#11 library for Android or iOS, would have any suggestion about how we can address this?

Regards

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
