### ISSUE TITLE
is Pkcs11Interop support secp256k1 (the Bitcoin curve)?

### ISSUE THREAD

**Issue by r-anjirabi** [Pkcs11Interop/Pkcs11Interop#209]

**Comment by jariq** [comment]
That is an incorrect question because Pkcs11Interop is just a simple C# wrapper that calls C functions exported by native PKCS#11 library. The correct question would be: Does PKCS#11 library provided by my device manufacturer support secp256k1?

Ask your device manufacturer.

**Comment by jariq** [comment]
`secp256k1` is not mechanism. It's just the name of elliptic curve parameters. You'll usually use EC keys with `CKM_ECDSA`.
