### ISSUE TITLE
Private key is not in certificate

### ISSUE THREAD

**Issue by dotnetclue** [Pkcs11Interop/Pkcs11Interop#213]
**Hi,
I want to ask a qusetion according to my code, My code is as bellow:**
**in AuthenticateAsServer  I get "The server mode SSL must use a certificate with the associated private key" error cause privatekey is not in my certificate and also privatekey is not extractable from my HSM, would you please guid me what is the solution here?** 
**Thanks inadvance**

         static void ProcessClient(TcpClient client)
        {
            SslStream sslClientStream = new SslStream(client.GetStream(), true, AllowAnyServerCertificate, null, 
           EncryptionPolicy.RequireEncryption);

            try
            {
                X509Certificate2 _HsmserverCertificate = null;

                string pkcs11LibraryPath = "C:\\Program Files (x86)\\nCipher\\nfast\\toolkits\\pkcs11\\cknfast-64.dll";

                Pkcs11InteropFactories factories = new Pkcs11InteropFactories();

                using (IPkcs11Library pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, pkcs11LibraryPath, 
                   AppType.MultiThreaded))
                {
                    ISlot slot = HelpersMethods.GetUsableSlot(pkcs11Library);

                    using (Net.Pkcs11Interop.HighLevelAPI.ISession session = slot.OpenSession(SessionType.ReadWrite))
                    {
                        session.Login(CKU.CKU_USER, @"1234");

                        var certificate = ReadCertificates(slot, session)[0];

                        _HsmserverCertificate = new X509Certificate2(certificate.CkaValue);
						
                        session.Logout();
                    }
                }

                sslClientStream.ReadTimeout = glb_intReciveTimeOut;
                sslClientStream.WriteTimeout = glb_intSendTimeOut;

                sslClientStream.AuthenticateAsServer(_HsmserverCertificate,
                                                     clientCertificateRequired: false,
                                                     SslProtocols.Tls12,
        }
	}
-------------------------------------------------------------------

**Comment by jariq** [comment]
SSL connections in .NET are managed by platform-specific native libraries, such as SChannel on Windows or OpenSSL on Linux. These native libraries cannot utilize an instance of the `X509Certificate2` class without an associated private key, as in your case. Additionally, they require a private key backed by their own unmanaged implementation of `AsymmetricAlgorithm`.

In other words, you cannot use Pkcs11Interop for SSL/TLS connections with the built-in network stack of .NET. You would need to write your own SSL/TLS implementation and integrate it with Pkcs11Interop. It is not a trivial task and requires a significant amount of work.
