### ISSUE TITLE
Missing attribute CKA_NAME_HASH_ALGORITHM

### ISSUE THREAD

**Issue by harrison314** [Pkcs11Interop/Pkcs11Interop#217]
In `CKA` enum missing value for `CKA_NAME_HASH_ALGORITHM` (with value `0x0000008CUL`) used for [X.509 public key certificate objects (specification 2.40)](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/os/pkcs11-base-v2.40-os.html#_Toc416959712).

**Comment by jariq** [comment]
Thank you for reporting the bug in Pkcs11Interop. I truly appreciate the time and effort you invested in identifying the issue. I will ensure it is fixed in the next release.
