### ISSUE TITLE
problem in Pkcs11Interop with new dll from epass 2003

### ISSUE THREAD

**Issue by myousry35** [Pkcs11Interop/Pkcs11Interop#218]
dear sir,
IPkcs11Library pkcs11Library = factories.Pkcs11LibraryFactory.LoadPkcs11Library(factories, DllLibPath, AppType.MultiThreaded);
give null value ptr with new dll from epass 2003 version1.1.22.729 with feitian token
will be there an update or a fix for this problem package Pkcs11Interop 5.1.2
thanks for your patience

**Comment by jariq** [comment]
Could you please include the logs generated by [PKCS11-LOGGER](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/doc/TROUBLESHOOTING.md) while running your application? This will help me understand and address the problem more precisely.

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.
