### ISSUE TITLE
CKR_OPERATION_NOT_INITIALIZED in multithreaded application

### ISSUE THREAD

**Issue by BaerMitUmlaut** [Pkcs11Interop/Pkcs11Interop#219]
I'm working on a multithreaded application and I'm currently having some trouble with a CKR_OPERATION_NOT_INITIALIZED error thrown in the last line of this block: https://github.com/Pkcs11Interop/Pkcs11Interop/blob/47e4e17af64cc9cd46460022e056c49505fbe5fd/src/Pkcs11Interop/HighLevelAPI41/Session.cs#L991-L998

<details><summary>Screenshot</summary>

![grafik](https://user-images.githubusercontent.com/9693842/217844420-529b0a22-e35a-4e2d-8863-9a1d306bddec.png)

</details>

As far as I understand, this error is thrown when the encryption or decryption operation is not initialized and from what I've read, an operation stays initialized until data is decrypted. My best guess is that the following is happening:
| Thread A      | Thread B      | Initialized |
|---------------|---------------|-------------|
| C_DecryptInit |               | Yes         |
|               | C_DecryptInit | Yes         |
| C_Decrypt     |               | No          |
|               | C_Decrypt     | ⚡           |

Thus a lock would be required to make the call to `Session.Encrypt` / `Session.Decrypt` thread safe.

**Comment by jariq** [comment]
PKCS#11 provides thread safety by utilizing separate session objects. Each thread should use its own distinct session to avoid conflicts. This approach maintains the integrity of operations without requiring additional locking mechanisms.

You might also find the [Pkcs11Interop.X509Store](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store) library to be a simpler and more user-friendly alternative to the full Pkcs11Interop. Pkcs11Interop.X509Store is designed to prevent incorrect usage of the API, making it easier to achieve your goals without running into common pitfalls. The FAQ contains [tips for correct usage in multithreaded applications](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/master/doc/05_FAQ.md#can-i-use-pkcs11interopx509store-in-a-multi-threaded-application).

If you have any further questions or need assistance, feel free to reach out!
