### ISSUE TITLE
Missing param represents object handle

### ISSUE THREAD

**Issue by harrison314** [Pkcs11Interop/Pkcs11Interop#220]
In `IMechanismParamsFactory` missing method for create `CK_OBJECT_HANDLE` as mechanism parameter.

For example, it is used from `CKM_CONCATENATE_BASE_AND_KEY` - <https://www.cryptsoft.com/pkcs11doc/v220/group__SEC__12__34__3__CONCATENATION__OF__A__BASE__KEY__AND__ANOTHER__KEY.html#CKM_CONCATENATE_BASE_AND_KEY>.

**Comment by jariq** [comment]
Closing as a duplicate of #145.
