### ISSUE TITLE
Incorrect CK_VERSION string value

### ISSUE THREAD

**Issue by AlexSynakh** [Pkcs11Interop/Pkcs11Interop#222]
Hi, it seems that `CK_VERSION.ToString` method is returning incorrect value.

I'm currently using Pkcs11Interop 5.1.2 library and it is returning `FirmwareVersion = 7.2` instead of `FirmwareVersion = 7.02`.
According to [PKCS#11 v2.40](https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.40) section 3.1, minor version number is the hundredth portion of the version. Provided example in PKCS#11 specification shows that `CK_VERSION { major = 2, minor = 1 }` is 2.01 version

So, in order to correctly display version string, `CK_VERSION.ToString` method implementation should be something like this:
```csharp
public override string ToString()
{
    if (Minor[0] == 0) 
    {
        return string.Format("{0}.{1}", Major[0], Minor[0]);
    }

    return string.Format("{0}.{1:D2}", Major[0], Minor[0]);
}
```

**Comment by jariq** [comment]
Thank you for reporting the bug in Pkcs11Interop. I truly appreciate the time and effort you invested in identifying the issue. I will ensure it is fixed in the next release.
