### ISSUE TITLE
Get Key Value From HSM

### ISSUE THREAD

**Issue by yigitbozkurt** [Pkcs11Interop/Pkcs11Interop#223]
How can i get value of a key from hsm

**Comment by jariq** [comment]
Unfortunately, your question is quite broad, making it difficult to provide a specific answer. I recommend reviewing [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/blob/master/v2.20/pkcs-11v2-20.pdf), which might help you find the information you need. If you have more specific questions in the future, please feel free to ask.
