### ISSUE TITLE
Not able to use C_Sign with yubikey PIV slot with CKA_ALWAYS_AUTHENTICATE 

### ISSUE THREAD

**Issue by mmoraga** [Pkcs11Interop/Pkcs11Interop#224]
I'm having issues using `C_Sign` functions on a yubikey when the certificate is stored in slot 9c (which enforces CKA_ALWAYS_AUTHENTICATE).

I checked the Cryptoki specs and Pkcs11Interop implementation: https://github.com/Pkcs11Interop/Pkcs11Interop/blob/47e4e17af64cc9cd46460022e056c49505fbe5fd/src/Pkcs11Interop/HighLevelAPI40/Session.cs#L1510 

which does the C_SignInit, C_Login with CKU_CONTEXT_SPECIFIC before calling C_Sign

but I keep getting  `CKR_DATA_INVALID` errors

I'm also contacting yubico to see if it might be an issue on their end. Although the same key and certificate works fine on windows where we use a different API for the certificate operation, so I'm suspecting this might be an issue in Pkcs11Interop.

**Comment by jariq** [comment]
Please [collect logs with PKCS11-LOGGER](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/master/doc/TROUBLESHOOTING.md) and attach them to this issue.

**Comment by mmoraga** [comment]
Here you go:

[pkcs11.log](https://github.com/Pkcs11Interop/Pkcs11Interop/files/12250839/pkcs11.log)

Do you also want logs from a successful run for when `CKA_ALWAYS_AUTHENTICATE` is false?

btw the macOS build script for the pkcs11-logger is a bit outdated, do you want me to open a PR with an updated one? (x32 is no longer supported, so can change it to produce x64, arm64 and/or universal lib instead)

**Comment by jariq** [comment]
> Do you also want logs from a successful run for when CKA_ALWAYS_AUTHENTICATE is false?

I don't think it would help.

> btw the macOS build script for the pkcs11-logger is a bit outdated, do you want me to open a PR with an updated one?

Sure, go ahead if you have time for that. However I cannot promise when I'll merge it.

> Here you go: `pkcs11.log`

I've extracted signing part (see bellow) and as far as Pkcs11Interop is concerned everything looks fine there. It was unmanaged library that returned `CKR_DATA_INVALID` so you need to consult the reason with its producer. I can see you have already created issue - https://github.com/Yubico/yubico-piv-tool/issues/443 - so you can wait for a response from maintainer or you can investigate it yourself. In this case source code of PKCS#11 library is available: https://github.com/Yubico/yubico-piv-tool/tree/master/ykcs11

```
0x00008b24 : 0x000000000014997a : ****************************** 2023-08-03 14:29:49 ***
0x00008b24 : 0x000000000014997a : Calling C_SignInit
0x00008b24 : 0x000000000014997a : Input
0x00008b24 : 0x000000000014997a :  hSession: 105553116705584
0x00008b24 : 0x000000000014997a :  pMechanism: 0x30d5fce48
0x00008b24 : 0x000000000014997a :   mechanism: 66 (CKM_SHA512_RSA_PKCS)
0x00008b24 : 0x000000000014997a :   pParameter: 0x0
0x00008b24 : 0x000000000014997a :   ulParameterLen: 0x0
0x00008b24 : 0x000000000014997a :  hKey: 105553132473248
0x00008b24 : 0x000000000014997a : Returning 0 (CKR_OK)
0x00008b24 : 0x000000000014997a : ****************************** 2023-08-03 14:29:49 ***
0x00008b24 : 0x000000000014997a : Calling C_Login
0x00008b24 : 0x000000000014997a : Input
0x00008b24 : 0x000000000014997a :  hSession: 105553116705584
0x00008b24 : 0x000000000014997a :  userType: 2 (CKU_CONTEXT_SPECIFIC)
0x00008b24 : 0x000000000014997a :  pPin: 0x18e411618
0x00008b24 : 0x000000000014997a :  *pPin: *** Intentionally hidden ***
0x00008b24 : 0x000000000014997a :  ulPinLen: 6
0x00008b24 : 0x000000000014997a : Returning 0 (CKR_OK)
0x00008b24 : 0x000000000014997a : ****************************** 2023-08-03 14:29:49 ***
0x00008b24 : 0x000000000014997a : Calling C_Sign
0x00008b24 : 0x000000000014997a : Input
0x00008b24 : 0x000000000014997a :  hSession: 105553116705584
0x00008b24 : 0x000000000014997a :  pData: 0x18e3cc650
0x00008b24 : 0x000000000014997a :  *pData: HEX(323032332D30382D30335431323A32393A34392E333836393036305A)
0x00008b24 : 0x000000000014997a :  ulDataLen: 28
0x00008b24 : 0x000000000014997a :  pSignature: 0x0
0x00008b24 : 0x000000000014997a :  pulSignatureLen: 0x30d5fce38
0x00008b24 : 0x000000000014997a :  *pulSignatureLen: 0
0x00008b24 : 0x000000000014997a : Output
0x00008b24 : 0x000000000014997a :  pSignature: 0x0
0x00008b24 : 0x000000000014997a :  pulSignatureLen: 0x30d5fce38
0x00008b24 : 0x000000000014997a :  *pulSignatureLen: 256
0x00008b24 : 0x000000000014997a : Returning 0 (CKR_OK)
0x00008b24 : 0x000000000014997a : ****************************** 2023-08-03 14:29:49 ***
0x00008b24 : 0x000000000014997a : Calling C_Sign
0x00008b24 : 0x000000000014997a : Input
0x00008b24 : 0x000000000014997a :  hSession: 105553116705584
0x00008b24 : 0x000000000014997a :  pData: 0x18e3cc650
0x00008b24 : 0x000000000014997a :  *pData: HEX(323032332D30382D30335431323A32393A34392E333836393036305A)
0x00008b24 : 0x000000000014997a :  ulDataLen: 28
0x00008b24 : 0x000000000014997a :  pSignature: 0x18e411708
0x00008b24 : 0x000000000014997a :  pulSignatureLen: 0x30d5fce38
0x00008b24 : 0x000000000014997a :  *pulSignatureLen: 256
0x00008b24 : 0x000000000014997a : Returning 32 (CKR_DATA_INVALID)
```

**Comment by mmoraga** [comment]
Thank you, I will try to investigate further with the library vendor.

I had to build the logger to get it running on my machine anyway, so might as well share it with others: https://github.com/Pkcs11Interop/pkcs11-logger/pull/15

**Comment by mmoraga** [comment]
Closing this as it wasn't an issue with Pkcs11Interop.
