### ISSUE TITLE
mac os compile problem MAUI .net core 7.0 how to fix ?

### ISSUE THREAD

**Issue by Ochirsugir** [Pkcs11Interop/Pkcs11Interop#226]
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.4.60/targets/Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
Undefined symbols for architecture x86_64:
  "_C_CancelFunction", referenced from:
     -u command line option
  "_C_CloseAllSessions", referenced from:
     -u command line option
  "_C_CloseSession", referenced from:
     -u command line option
  "_C_CopyObject", referenced from:
     -u command line option
  "_C_CreateObject", referenced from:
     -u command line option
  "_C_Decrypt", referenced from:
     -u command line option

**Comment by jariq** [comment]
At this time, MacCatalyst apps are not supported by Pkcs11Interop 5. I apologize for any inconvenience this may cause.

Thank you for your understanding.
