### ISSUE TITLE
C_Sign returned CKR_OPERATION_NOT_INITIALIZED in multithreaded application

### ISSUE THREAD

**Issue by Anil-Kamble** [Pkcs11Interop/Pkcs11Interop#229]
Hi,

We are signing the PDF using multi threading. Sometimes it's throwing error "C_Sign returned CKR_OPERATION_NOT_INITIALIZED" & "C_SignInit returned CKR_OPERATION_ACTIVE"

It will be great help, if anyone could guide us to resolve it.

Stacktrace is also pasted below for reference.

at Net.Pkcs11Interop.HighLevelAPI41.Session.Sign(IMechanism mechanism, IObjectHandle keyHandle, Byte[] data, Boolean performLogin, Byte[] keyPin)
   at Net.Pkcs11Interop.HighLevelAPI41.Session.Sign(IMechanism mechanism, IObjectHandle keyHandle, Byte[] data)

**Comment by jariq** [comment]
My guess is that you might not be using PKCS#11 correctly in a multithreaded application.

You have two options to proceed:

1. **Create an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) (Minimal, Complete, and Verifiable Example):**  
   Please create a small, self-contained example that replicates the issue you are encountering. Along with this example, kindly include the logs generated by [PKCS11-LOGGER](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/doc/TROUBLESHOOTING.md) while running the MCVE. This will help me understand and address the problem more precisely.

2. **Consider using [Pkcs11Interop.X509Store](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store):**  
   You might find the Pkcs11Interop.X509Store library to be a simpler and more user-friendly alternative to the full Pkcs11Interop. Pkcs11Interop.X509Store is designed to prevent incorrect usage of the API, making it easier to achieve your goals without running into common pitfalls. The FAQ contains [tips for correct usage in multithreaded applications](https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/master/doc/05_FAQ.md#can-i-use-pkcs11interopx509store-in-a-multi-threaded-application).

Please let me know how you would like to proceed or if you have any further questions.

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.
