### ISSUE TITLE
Support for Cryptosec PCI V1.1 by Realsec

### ISSUE THREAD

**Issue by aradhwan** [Pkcs11Interop/Pkcs11Interop#23]
I tried to use the library with cryptosec HSM but with no hope. Just want to ask if this HSM is supported or not ?
The library they provided with the HSM called "cryptosec.dll"

**Comment by jariq** [comment]
I have no previous experience with [Realsec Cryptosec PCI v.1.1 HSM](http://www.realsec.com/en/solutions/general-purpose/hsm-hardware-security-module/cryptosec-pci-v-1-1/) but "Standard PKCS#11 interface" is listed as one of the main features on their website so it should work with Pkcs11Interop just like any other PKCS#11 compliant device. Can you please provide more details on the problem you have experienced? Did Pkcs11Interop throw some exception?

**Comment by aradhwan** [comment]
Hello Jariq, thanks a lot for your comment.
This is the exception I am getting:
An unhandled exception of type 'Net.Pkcs11Interop.Common.UnmanagedException' occurred in Pkcs11Interop.dll

Additional information: Unable to load library: %1 is not a valid Win32 application.

Environment: Windows Server 2012 R2 (64bit), visual studio 2013 and HighLevelAPI41

Note: I tried to use another library called "NCryptoki" and it is working fine together with the "cryptosec.dll"

**Comment by jariq** [comment]
You are most likely just trying to load 32-bit library into 64-bit application. Please take a look at [this similar thread](https://groups.google.com/d/msg/pkcs11interop/h6NR-QZzegw/3o_QWjToC5sJ) for more details and let me know if you need further explanation.

**Comment by aradhwan** [comment]
This is 100 % Correct,
I am developing windows forms application and the platform target for my app is "Any CPU". However, there is one check-box option that I haven't noticed which is "Prefer 32-bit", it is located in Project Menu --> properties --> Build --> General --> Platform Target, by unchecking this option the library worked so well.
Thank you so much for your help Jariq
