### ISSUE TITLE
C_FindObjects does return with nothing while running application in docker

### ISSUE THREAD

**Issue by vgary06** [Pkcs11Interop/Pkcs11Interop#232]
Pkcs11Interop version: 5.1.2
Application platform: Linux container running on Win64 Docker-Desktop
CryptoServer: The same Win64 machine

**Scenario:** 
C# .net6.0 application works pretty well with this nuget. Can log into the server and able to run functions as well.
But when I change the environment to run it in docker makes the results weird.

Test steps while run in docker (aspnet-6.0 microsoft/ linux container):
1. Using library 'libcs_pkcs11_R3.so' because I am trying to connect to a remote cryptoserver - running on Win - from linux environment.
2. Login successful, getting slot with openning session also works well.
3. Try to find an object with Session.FindAllObjects() and here something happens:

-        Docker: the Pkcs11Interop creates an 8 bytes long **API80** Session because I assume I run it in Linux 64 ( [aspnet-6.0 docker image](https://hub.docker.com/_/microsoft-dotnet-aspnet/) ):
          In this case there is no way to get any of the object from the cryptoserver

The `objectCount` always 0 and I don't change the **IObjectAttribute** preferences nor the calling method, only started to run it in docker and used the linux library (*.so) for it.
`rv = _pkcs11Library.C_FindObjects(_sessionId, objects, objectsLength, ref objectCount);`

-        Without Docker: the Pkcs11Interop creates a 4 bytes long **API41** Session because I run it in Win64 (of course that case using the *.DLL win library to connect):
          In this case it's OK and get the object.

What happens when the application runs in docker/linux and why cannot get any of the objects with the find functions? There was no luck with the `_FindAllObjects(attr)_` nor with the `_FindObjects(count)_`.

P.S.: it looks like the other functions (verify, sign, encrypt, decrypt) works well in docker... only the FindObject has this "problem".

**Comment by jariq** [comment]
In my professional opinion the problem you are experiencing is not related to Pkcs11Interop and you should be discussing it with CryptoServer support team. However if you want to explore the world of segfaults and other magical crashes then you can force Pkcs11Interop to use different set of LowLevelAPIs by manually changing the values of [`Net.Pkcs11Interop.Common.Platform.NativeULongSize`](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/src/Pkcs11Interop/Common/Platform.cs#L146) and [`Net.Pkcs11Interop.Common.Platform.StructPackingSize`](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/src/Pkcs11Interop/Common/Platform.cs#L186). May the force be with you :godmode:

**Comment by vgary06** [comment]
The cryptoserver manufacturer is Utimaco. I tried to look after their documentations but nothing relates to this kind of issue. As I said the interesting thing is the other functions works pretty well.
I will check these Platform static properties. Is there a way to change them to mock as they use a 4 byte platform settings?
And maybe you can help with one thing - if I cannot find object but create - there is a way to store the created object(secret, key, key-pair) on the cryptoserver?
I can generate a RSA/AES key that can be found on server after their creation with logged in user by their (utimaco) P11 CAT tool. But whether my application generate a key I cannot persist/store or save it anywhere to find and get back after its process done.

**Comment by vgary06** [comment]
Done. It was the misconfigured line of the cryptoserver's configuration... Thanks the tip to check the Platform fields. It wasn't the issue that caused the problem but was very helpful.
