### ISSUE TITLE
session.Decrypt returning garbage characters appended in PKCS#11 Multipart Decryption with Pkcs11Interop v 4.x.x

### ISSUE THREAD

**Issue by tankhare** [Pkcs11Interop/Pkcs11Interop#234]
Hello,

We are working on HSM integration with Client Application who is using Pkcs11Interop wrapper v4.0.0.

Almost, all operations are successful except Multi-part decryption where we are getting garbage characters at the end of original data. There is no error or exception. All HSM calls are successful. HSM logs shows data without any garbage characters. Even we tried to debug Pkcs11Interop library where the output stream object under Decrypt method (HighLevelAPI 41) is getting correct data. 

But when it is being copied to MemoryStream and being written garbage characters are being added to it. We tried to investigate further and we found that after coping data to MemoryStream if we try to print the MemoryStream.ToString() value it is returning exactly the same data which is being added to the actual data. So, we are not sure whether this is an expected behavior and we are not handling this correctly or it is a known issue which has been fixed in later versions. We have tested this issue with Interop versions - v4.0.0, v4.0.0.2 v4.1.0 v4.1.1 v4.1.2 ). Any help would be appreciated.

I am attaching a document where I have tried to explain it in detail. Please let us know if we are missing something. 

Thanks,
Tanmay

[Pkcs11Interop_v_4.0.0_MultiPart_Decrypt_Issue.pdf](https://github.com/Pkcs11Interop/Pkcs11Interop/files/14469726/Pkcs11Interop_v_4.0.0_MultiPart_Decrypt_Issue.pdf)

**Comment by jariq** [comment]
Hello @tankhare could you please:
1. create [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) that replicates your issue
2. and attach [PKCS11-LOGGER output](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.1.2/doc/TROUBLESHOOTING.md) created when running your MCVE

Thanks

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.
