### ISSUE TITLE
Getting a shared unique identifier for a smart card using PKCS#11 and CSP/minidriver

### ISSUE THREAD

**Issue by Murhaf-Mo** [Pkcs11Interop/Pkcs11Interop#236]
Hey there, 

I've been working on a project that involves accessing info on a smart card using PKCS#11, and your Pkcs11Interop library has been a lifesaver. Thanks for all the hard work you've put into it!

I've been trying to find a way to get a unique identifier for a smart card using PKCS#11, and I was wondering if you could point me in the right direction. I know that smart cards usually have a unique Card ID or GUID that can be used to tell them apart, but I'm not sure how to get that info through PKCS#11.

I did some digging and tried to get the Card ID and serial number using the smart card minidriver, but the values I got didn't match the serial number I retrieved through PKCS#11. It's left me a bit confused about how these identifiers work and if they're meant to be the same.

So, I guess my main question is: Is the serial number retrieved through PKCS#11 specific to the PKCS#11 interface, or is it supposed to match the identifiers accessible through the card's CSP or minidriver? If they're different, is there a way to get the same unique identifier using both methods? This is important because we are trying to support both interfaces.

If you have any resources, code samples, or just general advice on how to tackle this, I'd be super grateful.

Thanks in advance for any help you can provide and I appreciate you taking the time to assist me with this.

**Comment by jariq** [comment]
> Is the serial number retrieved through PKCS#11 specific to the PKCS#11 interface, or is it supposed to match the identifiers accessible through the card's CSP or minidriver?

IMO it is implementation specific and completely up to a smartcard software vendor.

PKCS#11 library you are using was written by someone (usually smartcard vendor) and that person/organization decided what will it return in `TokenInfo`. Also CSP/minidriver (they're both libraries installed in your system) you are using was written by someone (usually the same smartcard vendor) and that person/organization decided what information will it return. Information returned by PKCS#11 and CSP/minidriver may or may not be the same. It is completely up to their implementer.

> If they're different, is there a way to get the same unique identifier using both methods?

Your best bet is to consult this question with author/s of PKCS#11 library and CSP/minidriver libraries you are using.

**Comment by Murhaf-Mo** [comment]
Hey,

Thanks a bunch for the quick reply and advice! It's much appreciated.

Cheers,
Murhaf
