### ISSUE TITLE
Closing ALL open session - is it possible?

### ISSUE THREAD

**Issue by always-developing** [Pkcs11Interop/Pkcs11Interop#238]
Firstly, thank you for the library.

This is more of a question, than an issue.  Is it possible through the library to close all open sessions to a slot?

I am using the library to perform operations on the slot, as intended. As part of my testing I am using the pkcs11-tool command line too to try re-initialze a slot for testing purposes, and am getting a CKR_SESSION_EXISTS (0xb6) error returned.

At this time my application is not running, and as far as I can tell, nothing running actively has a session open. A reboot has had no effect.
I have tried calling the CloseAllSessions library method, but I suspect, as designed, this only closes sessions in the current process.

I'm looking for a way, preferably via the library, but via any other method/command line will do - for a way to close all open sessions to a slot? 

Any advice or input is appreciate.

**Comment by jariq** [comment]
> I am using the library to perform operations on the slot, as intended. As part of my testing I am using the pkcs11-tool command line too to try re-initialze a slot for testing purposes, and am getting a CKR_SESSION_EXISTS (0xb6) error returned.

This sounds more like an `pkcs11-tool` issue to me. I'd guess `pkcs11-tool` opened a session that needs to be closed. You could use [pkcs11-logger](https://github.com/Pkcs11Interop/pkcs11-logger) or OpenSC's own `pkcs11-spy` to analyze what actions `pkcs11-tool` performs.

**Comment by always-developing** [comment]
Thanks for the feedback @jariq . Managed to get to the source of the issue - there was a different process which had an open session to a **different slot**.  This was causing the re-initializing of my slot to give the error.
