### ISSUE TITLE
libdl.so problems on Ubuntu 24.04

### ISSUE THREAD

**Issue by Jakub1Cieslak** [Pkcs11Interop/Pkcs11Interop#239]
I wrote an app using the Pkcs11Interop library and am currently trying to run it on Ubuntu 24.04. When calling ```HighLevelAPI.Factories.Pkcs11LibraryFactory.LoadPkcs11Library()```, I am getting this error:
![obraz](https://github.com/Pkcs11Interop/Pkcs11Interop/assets/173045925/62bc0237-a710-4430-9b24-836a1ec03eb4)
From what I've been able to gather, this is an issue in Ubuntu versions past 20, as ```libdl.so``` is no longer supported in favour of ```libdl.so.2```. Creating a symlink so that the latter "impersonates" the former did not work for me. Is there any workaround for this, or does the library simply not support newer Ubuntu versions?

**Comment by jariq** [comment]
You need to map `libdl` to `libdl.so.2` in your application by using [DllImportResolver delegate](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.dllimportresolver?view=net-6.0) with [NativeLibrary.SetDllImportResolver method](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=net-6.0). Sample can be seen in https://github.com/Pkcs11Interop/Pkcs11Interop/issues/168#issuecomment-729985741 or in [Pkcs11LoggerTests project](https://github.com/Pkcs11Interop/pkcs11-logger/blob/master/test/Pkcs11LoggerTests/Settings.cs#L108-L113). More detailed explanation can be seen in https://github.com/Pkcs11Interop/Pkcs11Interop/pull/208#issuecomment-1173036742.

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.
