### ISSUE TITLE
Support native AOT

### ISSUE THREAD

**Issue by idan-h** [Pkcs11Interop/Pkcs11Interop#241]
Hey, is there any plan on supporting native AOT?

Marshalling is not supported, so it would require using unsafe.

I am willing to contribute if needed, tell me what you think

**Comment by jariq** [comment]
I currently have no intention to support native AOT in Pkcs11Interop. If you need this feature and are willing to invest your time in it then I guess it would be the best to start your own open source project. Good luck.

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.

**Comment by ceztko** [comment]
Any specific reason, other than lack of interest/time, for not supporting AOT? Unless you are doing a lot of reflection or relying on stuff that is not [AOT compatible](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet8#limitations-of-native-aot-deployment), ensuring the library is AOT compatible should be an easy task. In the mean time I just did an AOT publish on a small demo and it produced just the few warnings below. I will have a look at those soon.

```
3>/_/src/Pkcs11Interop/Common/UnmanagedMemory.cs(217,0): Warning IL3050: Net.Pkcs11Interop.Common.UnmanagedMemory.Read(IntPtr,Type): Using member 'System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr,Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available.
3>/_/src/Pkcs11Interop/Common/UnmanagedLibrary.cs(186,0): Warning IL3050: Net.Pkcs11Interop.Common.UnmanagedLibrary.GetDelegateForFunctionPointer<T>(IntPtr): Using member 'System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr,Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the delegate might not be available. Use the GetDelegateForFunctionPointer<TDelegate> overload instead.
3>/_/src/Pkcs11Interop/Common/UnmanagedMemory.cs(149,0): Warning IL3050: Net.Pkcs11Interop.Common.UnmanagedMemory.SizeOf(Type): Using member 'System.Runtime.InteropServices.Marshal.SizeOf(Type)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the SizeOf<T> overload instead.
3>/_/src/Pkcs11Interop/Common/UnmanagedMemory.cs(181,0): Warning IL3050: Net.Pkcs11Interop.Common.UnmanagedMemory.Write(IntPtr,Object): Using member 'System.Runtime.InteropServices.Marshal.StructureToPtr(Object,IntPtr,Boolean)' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Marshalling code for the object might not be available. Use the StructureToPtr<T> overload instead.
```

**Comment by ceztko** [comment]
It appears the GitHub user @imza-io was already working on this in a [fork](https://github.com/imza-io/pkcs11-interop). The amount of modifications needed to enable Native AOT compilation in Pkcs11Interop looks very small. I tested it already in my small demo and it works.
