### ISSUE TITLE
Unable to load library: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by bhavneetsinghthakur** [Pkcs11Interop/Pkcs11Interop#25]
i am getting above error please give me solution
i am using epass2003 token

**Comment by jariq** [comment]
You are most likely trying to load 32-bit unmanaged PKCS#11 library into 64-bit application or vice versa. Please take a look at [similar discussion](https://groups.google.com/d/msg/pkcs11interop/h6NR-QZzegw/3o_QWjToC5sJ ) for more details and let me know if you need further explanation.

**Comment by jariq** [comment]
Have you been able to resolve your problem with provided information?

**Comment by bhavneetsinghthakur** [comment]
yes thnks Jaroslav Imrich

is there any demo Application for Pkcs11Interop implementation...


On Tue, May 3, 2016 at 1:14 AM, Jaroslav Imrich <notifications@github.com>
wrote:

> Have you been able to resolve your problem with provided information?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Pkcs11Interop/Pkcs11Interop/issues/25#issuecomment-216341111>
>



-- 
Thanks & Regards
Bhavneet Singh Thakur
(Software Engineer)

Mobile: 09770112277
Pl. *Save a tree. Please don't print this e-mail unless you really need
to...*

**Comment by jariq** [comment]
Code samples can be found at https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.1.0/doc/CODE_SAMPLES.md

I am closing this issue since original problem has been resolved.

**Comment by bhavneetsinghthakur** [comment]
ok thnks again.........

On Tue, May 3, 2016 at 1:20 PM, Jaroslav Imrich <notifications@github.com>
wrote:

> Code samples can be found at
> https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.1.0/doc/CODE_SAMPLES.md
>
> I am closing this issue since original problem has been resolved.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Pkcs11Interop/Pkcs11Interop/issues/25#issuecomment-216461139>
>



-- 
Thanks & Regards
Bhavneet Singh Thakur
(Software Engineer)

Mobile: 09770112277
Pl. *Save a tree. Please don't print this e-mail unless you really need
to...*
