### ISSUE TITLE
how to create slot programmatically ?

### ISSUE THREAD

**Issue by yp25** [Pkcs11Interop/Pkcs11Interop#250]
I wonder if there is available function to create HSM slots programmatically using Pkcs11Interop. Please advice. Thank you in advance

**Comment by jariq** [comment]
The PKCS#11 standard does not provide a function for creating new slots. However, your PKCS#11 library vendor may have implemented this feature, so I recommend checking their documentation for further details.

**Comment by jariq** [comment]
I am closing this issue due to prolonged inactivity.
