### ISSUE TITLE
Question on Storing PIN as plaintext

### ISSUE THREAD

**Issue by ratihS** [Pkcs11Interop/Pkcs11Interop#26]
Hi Jariq,

One question I want to ask, using this interop means that the user password/PIN is stored in plaintext in the settings/ web config. Granted that the application will be within firewall, but do you foresee a security problem in this?
If so, do you have a suggestion on securing this PIN for login/open session.

Thank you kindly

**Comment by jariq** [comment]
> ...using this interop means that the user password/PIN is stored in plaintext in the settings/ web config...

No it does not. It is up to the library consumer to choose/implement the best method.

> ...do you have a suggestion on securing this PIN for login/open session.

It is very important to understand that PKCS#11 sessions share the login state - once any session is authenticated, all the other sessions (even those which are yet to be opened) are authenticated. That means you can perform login just once and your application/process is authenticated for the rest of its lifetime or until you perform logout.

These are some of the most common scenarios when it comes to PIN handling:

- use keys which are not protected by PIN (depending on HSM such keys can be used without authentication on the local machine but cannot be copied to any other machine)
- store encrypted PIN in web.config (see aspnet_regiis tool options)
- pass PIN as a parameter when application is started
- let your application ask for PIN with an interactive dialog
- pass PIN to the application using some IPC mechanism
- isolate the code which works with sensitive key material into a standalone process and consume its services using some IPC mechanism

Choosing the correct approach/architecture is a task that should be **very carefully considered** and ideally performed by a security professional - usually a guy with many years of experience in the area of information systems security holding a bunch of useful security certifications :wink:

**Comment by ratihS** [comment]
Hi Jariq,

Okay, now I understand the intention of this PIN in the config.

Thank you kindly :)
