### ISSUE TITLE
Better handling of attempts to load PKCS#11 library with incorrect bitness

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#28]
Pkcs11Interop 3.1 throws exception with hard to understand message **"Unable to load library: %1 is not a valid Win32 application"** when there is an attempt to load 32-bit PKCS#11 library in 64-bit runtime or 64-bit PKCS#11 library in 32-bit runtime. This problem seems to be hit quite frequently (e.g. in #25).

Code generating this message was removed in 4e456174d976980b1f5b6193a780c3dae992699a as a side effect of adding support for netstandard1.1 compatible platforms so this message should never appear in the exception again but I still believe such frequent error deserves its own exception type or at least exception message.

[ERROR_BAD_EXE_FORMAT](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx) error code returned by `Marshal.GetLastWin32Error()` seems to be a natural choice for detection whether there was an attempt to load PKCS#11 library with incorrect bitness but I am not sure whether the same error code is returned on all supported platforms so I will need to investigate this further and "manually" check the code (or find other solution) on all platforms.

Following table tracks my progress:

| Platform | Runtime| Solution
|:-------|:------|:----
| Windows&nbsp;10 | net20&nbsp;32-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | net20&nbsp;64-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | net40&nbsp;32-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | net40&nbsp;64-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | sl5&nbsp;32-bit | I can't get it working on 64-bit OS
| Windows&nbsp;10 | sl5&nbsp;64-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | corefx&nbsp;32-bit | GetLastWin32Error() returns 0xC1
| Windows&nbsp;10 | corefx&nbsp;64-bit | GetLastWin32Error() returns 0xC1
| Linux | mono/corefx | [5th byte of ELF binary](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header) provides architecture info
| Mac&nbsp;OS&nbsp;X | mono/corefx | [dlopen_preflight](https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen_preflight.3.html#//apple_ref/doc/man/3/dlopen_preflight) checks if the library architecture is compatible with the current process
| Android | Xamarin | [5th byte of ELF binary](https://en.wikipedia.org/wiki/Executable_and_Linkable_Format#File_header) provides architecture info
| iOS | Xamarin | PKCS#11 library is linked statically so it cannot be targeting invalid platform

**Comment by Goncharyk** [comment]
I cannot load library on Mac OS. For test i create a .NetCore console app on MacOS and when i try to load lib by **/usr/local/lib/libbeidpkcs11.4.3.0.dylib** path, i get an unhandled exception.

```
while (true)
            {
                try
                {
                    Pkcs11 pkcs11 = new Pkcs11("beid_ff_pkcs11.dll", AppType.SingleThreaded);

                    List<Slot> slots = pkcs11.GetSlotList(SlotsType.WithTokenPresent);
                    if (slots.Count > 0)
                    {
                        Console.WriteLine("All works");
                        break;
                    }
                    else
                    {
                        Console.WriteLine("Slots 0");
                    }
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
                finally
                {
                    Thread.Sleep(500);
                }
            }
                     
           
            Console.ReadKey();
```
Thats works on Windows, but when i changed lib path and run it on Mac OS, i have an exception that 
**unable to load 64-bit unmanaged library into 32-bit runtime**

**Comment by Goncharyk** [comment]
I want to write a Xamarin.Mac app
