### ISSUE TITLE
Backward compatibility on PKCS v2.10

### ISSUE THREAD

**Issue by ratihS** [Pkcs11Interop/Pkcs11Interop#29]
Hi Jariq,

I want to check since this wrapper is using v2.20 of PKCS 11, some of the mechanism used is different compare to v2.10. I found out that our firmware HSM is still using v2.10 so do you mind telling me if I can use the method with the old mechanism, if so, how?
For example: I want to use C_DeriveKey with mechanism CKM.DES3_DERIVE_ECB, which in v2.20 replaced by CKM_DES3_ENCRYPT_DATA.
When I list down the mechanism using the wrapper, I couldn't see this specific one.

Thank you kindly for any guidance you could give me,

Ratih

**Comment by jariq** [comment]
CKM_DES3_DERIVE_ECB is vendor specific mechanism and AFAIK it has never been included in any version of PKCS#11 standards. However when you can't find desired mechanism in CKM enum and you know its numeric value you can use ulong variable instead (see [previous discussion about CKM_DES3_DERIVE_ECB mechanism](https://github.com/Pkcs11Interop/Pkcs11Interop/issues/10#issuecomment-37724476) for more details).

**Comment by jariq** [comment]
Any update on this? Was provided link helpful?

**Comment by ratihS** [comment]
Hi Jariq,

Thank you for your answer, it was really helpful. Managed to implement the mechanism.
So sorry for the late response.

Ratih
