### ISSUE TITLE
Pkcs11Interop and PGP

### ISSUE THREAD

**Issue by zosocanuck** [Pkcs11Interop/Pkcs11Interop#31]
Hi,

Does anyone have any experience integrating OpenPGP functionality with Pkcs11Interop?

Regards,
Ivan

**Comment by jariq** [comment]
There is a [technical proposal for an extension of the PKCS #11 specification with OpenPGP support](http://openfortress.nl/doc/spec/pgp-in-pkcs11/) but it has never been merged to the official specification and I am also not aware of any PKCS#11 library supporting it.

However all the things mentioned in that proposal seem to be compatible with the current Pkcs11Interop API and should present any problem once you find unmanaged library/device supporting it. 

Can you please share more information about your use case?

**Comment by Ba5har** [comment]
@zosocanuck may you share your experience integrating OpenPGP with Pkcs11Interop. Is there any update that you can give?
