### ISSUE TITLE
GetSlotList returns empty list after accessing X509Certificate2.PrivateKey

### ISSUE THREAD

**Issue by prarnok** [Pkcs11Interop/Pkcs11Interop#35]
Hi,
In my setup, the X509Certificate2 is stored in the server's Local Machine cert store and the keys are stored on a SafeNet HSM.
I downloaded Pkcs11Interop V2.0.1 the other day along with the Pkcs7SignatureGenerator.
I've created a simple WinForms test app to try this component.

When I access the Pkcs11Interop via the Pkcs7SignatureGenerator using the following code without trying to access the signing certificate's private key then a signature is generated as expected. 

                using (Pkcs7SignatureGenerator pkcs7SignatureGenerator = new Pkcs7SignatureGenerator(pkcs11Dll, tokenSerial, tokenLabel, pin, keyLabel, keyId, hashAlgorithm))
                {
                    X509Certificate2 intermediaryCertificate = CertUtils.LoadIntermediaryCertificate(this.signingCertificate, StoreLocation.LocalMachine);
                    X509Certificate2 rootCertificate = CertUtils.LoadRootCertificate(intermediaryCertificate, StoreLocation.LocalMachine);

                    List<X509Certificate2> otherCertificates = new List<X509Certificate2>();
                    otherCertificates.Add(intermediaryCertificate);
                    //Seem to need the root certificate for checking trusted chain even though not included in PKCS7 message signature.
                    otherCertificates.Add(rootCertificate);

                    // Build certification path for the signing certificate
                    ICollection<Org.BouncyCastle.X509.X509Certificate> certPath = CertUtils.BuildCertPath(this.signingCertificate, otherCertificates, false); //Exclude root certificate.

                    // Generate detached PKCS#7 signature
                    byte[] signedData = pkcs7SignatureGenerator.GenerateSignature(this.dataBytesToSign, true, CertUtils.ToBouncyCastleObject(signingCertificate), certPath);

                    response.Tag = Convert.ToBase64String(signedData);
                }

NB. In the above example the Pkcs7SignatureGenerator constructor "keyLabel" and "keyId" parameters are hard-coded but I'd like to derive them via the certificate.

If I run the following code before the Pkcs7SignatureGenerator code, an empty slot list is returned by the Pkcs7SignatureGenerator "FindSlot" method.

            using (System.Security.Cryptography.RSACryptoServiceProvider rsa = (System.Security.Cryptography.RSACryptoServiceProvider)signingCertificate.PrivateKey)
            {
                string containerName = rsa.CspKeyContainerInfo.KeyContainerName;
            }

After running the code through the PKCS11Logger the last 4 lines in the log file are:
0x00003050 : 0x000037c8 : Calling C_Finalize
0x00003050 : 0x000037c8 : Input
0x00003050 : 0x000037c8 :  pReserved: 0000000000000000
0x00003050 : 0x000037c8 : Returning 400 (CKR_CRYPTOKI_NOT_INITIALIZED)

I was hoping to use the KeyContainerName to get the private key ID via the Pkcs11Explorer.

It seems odd that accessing the HSM via the certificate's private key causes the Pkcs11Interop to return an empty slot list. It's as if accessing the private key like this opens a session which isn't closed properly.

I then ran a second instance of my test harness which only called the Pkcs7SignatureGenerator and didn't access the certificate private key. This instance worked fine.

Any suggestions for what might be happening would be appreciated.
Let me know if you need any more information.

Many thanks,
Mark

**Comment by jariq** [comment]
> I downloaded Pkcs11Interop V2.0.1 the other day along with the Pkcs7SignatureGenerator.

It is quite an old code which needs to be updated to use at least Pkcs11Interop 3.1.0.

> I was hoping to use the KeyContainerName to get the private key ID via the Pkcs11Explorer.

I am not quite sure why would you want to do that but it should be fairly easy to map `X509Certificate2` class instance to `Certificate` class instance by comparing `X509Certificate2.RawData` with `Certificate.Data`.

Corresponding `PrivateKey` class instance then can be found by comparing `PrivateKey.Id` with `Certificate.Id` and `PrivateKey.Label` with `Certificate.Label`. However please note that this may not always work because such association is not required by PKCS#11 specification. To be 100% sure you will need to compare also `PrivateKey.PublicKey` with `Certificate.PublicKey`.

> It seems odd that accessing the HSM via the certificate's private key causes the Pkcs11Interop to return an empty slot list. It's as if accessing the private key like this opens a session which isn't closed properly.

It is rather unusual to use both CSP and PKCS#11 providers in single application because often they share the same underlying code and may be interfering. Such problems are not easy to troubleshoot without the assistance of device vendor.

**Comment by prarnok** [comment]
Thanks for the heads up regarding v3 of pkcs11interop.dll. I just got v2 via a link on stackoverflow.

Your suggestion about converting the X509Certificate2 into a Certificate appears to have done the trick!

        private PrivateKey GetCertPrivateKey()
        {
            PrivateKey certificatePrivateKey = null;

            Certificate tmpCert = new Certificate("Foo", "Bar", this.signingCertificate.RawData);

            foreach (PrivateKey pk in this.privateKeys)
            {
                if (tmpCert.PublicKey.Equals(pk.PublicKey))
                {
                    certificatePrivateKey = pk;
                    break;
                }
            }

            return certificatePrivateKey;
        }


Thanks for your help,
Mark
