### ISSUE TITLE
How to implement extensions

### ISSUE THREAD

**Issue by sefai** [Pkcs11Interop/Pkcs11Interop#36]
Hello all,

First of all, thank you for providing this good quality library.

The module I am using provides some extended functionality. Is there a way to implement this functionality using Pkcs11Interop?

Kind Regards,

**Comment by jariq** [comment]
Can you please be more specific what kind of extended functionality are we talking about? Custom mechanisms, methods, defines or something else?

Generally speaking Pkcs11Interop has been specifically designed to support vendor specific extensions of almost any kind. For example there are three code samples available demonstrating how to correctly implement vendor specific functions:

* Test file: [HighLevelAPI/_28_Pkcs11ClassExtensionTest.cs](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_28_Pkcs11ClassExtensionTest.cs)
Demonstrates how to extend Pkcs11 classes with the ability to call C_GetUnmanagedStructSizeList vendor specific function of [PKCS11-MOCK](https://github.com/Pkcs11Interop/pkcs11-mock) module.

* Test file: [HighLevelAPI/_29_SlotClassExtensionTest.cs](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_29_SlotClassExtensionTest.cs)
Demonstrates how to extend Slot classes with the ability to call C_EjectToken vendor specific function of [PKCS11-MOCK](https://github.com/Pkcs11Interop/pkcs11-mock) module.

* Test file: [HighLevelAPI/_30_SessionClassExtensionTest.cs](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/src/Pkcs11Interop/Pkcs11InteropTests/HighLevelAPI/_30_SessionClassExtensionTest.cs)
Demonstrates how to extend Session classes with the ability to call C_InteractiveLogin vendor specific function of [PKCS11-MOCK](https://github.com/Pkcs11Interop/pkcs11-mock) module.

**Comment by sefai** [comment]
Thank you @jariq 

This is what I have been looking for. Strange that I couldn't find this through the Search Repo functionality, maybe I was using the wrong keywords...

**Comment by jariq** [comment]
I wonder if you have been able to successfully complete your task. Could you please share your experience? It might be helpful for other users and valuable for the future development of Pkcs11Interop library.
