### ISSUE TITLE
Q: how sign dll, msi, activex with pkcs11 module

### ISSUE THREAD

**Issue by mahdiit** [Pkcs11Interop/Pkcs11Interop#37]
Is there any guide how sign dll, msi, activex, with token or smartcard ? 

I can not find , there are many example that do it with pfx file but there is not any guide with this

Any help?

**Comment by jariq** [comment]
https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/build/sign-all.bat

**Comment by mahdiit** [comment]
Tanx but my private is in token, how tell signtool to read token device ?

**Comment by mahdiit** [comment]
Hi
i can not sign my dll , msi package using signtool that is in windows sdk, becuase my certificate stored in hardware token, 

i found a signtool from DigiCert that detect it and sign from PKCS moudle 
https://www.digicert.com/code-signing/digicert-certificate-utility-to-sign-code.htm
