### ISSUE TITLE
Invalid signature verify on Linux(x64)

### ISSUE THREAD

**Issue by cp293900** [Pkcs11Interop/Pkcs11Interop#40]
Hi
I use my smart card to do a signature, but different results on Windows and Linux.

My environment:
1. Windows 8(x64) VS 2013 using HighLevelAPI
2. Ubuntu 16.04(x64) Mono using HighLevelAPI

My signature result:
Source data: "Hello World"
The result on Linux:
A8-EA-22-F6-BE-8E-D3-A4-7F-38-6F-FA-C2-FC-2D-FA-4A-58-77-D6-96-8C-B5-97-BD-90-AF-C7-C0-DF-F4-7B-41-02-EA-9E-72-96-F6-0F-CD-A5-BF-49-53-E0-42-03-15-8D-BA-53-B9-75-B6-B5-9C-D8-A4-2B-69-DC-C6-5E-99-26-FE-0A-1F-D4-D8-78-C1-FC-7A-B7-FC-4D-03-25-AE-87-7E-60-A8-80-9F-81-79-FF-C0-75-C0-5C-61-AE-F8-B9-03-7F-E3-1E-60-81-38-F3-96-52-4D-8A-6C-73-98-10-C9-C9-73-1A-47-90-1D-93-76-D3-13-53-68-7D-08-28-0A-A4-60-9E-FD-49-D5-5E-69-5D-28-A0-50-3A-A8-36-70-5E-4F-3E-93-41-09-61-8F-AD-2B-A0-39-3E-09-49-3C-E8-90-0A-0B-2D-41-C9-F9-50-01-59-FF-C1-1D-C2-B6-21-C6-45-58-40-6F-41-16-58-14-D7-6E-A8-CC-7D-3F-78-C5-BD-51-BF-AF-09-59-2D-E7-82-E9-CE-29-2C-BB-65-9A-2B-2E-83-B9-CE-54-CF-31-2D-76-30-03-3F-2F-7B-E1-DD-99-CC-47-94-15-A3-6E-CF-CA-6A-98-FA-F6-1A-D9-D2-93-E2-91-77-98-EF-25-E7-F7-C4

The result on Windows:
AA-CC-D9-06-A3-1A-15-B6-87-76-23-20-DB-91-00-47-1C-9B-43-63-FA-80-EB-5D-56-78-76-87-57-56-B0-B0-14-29-EB-7D-2D-68-2F-01-3E-8D-80-FF-38-B3-60-09-E9-05-91-78-0B-D6-69-D4-C0-C6-96-D3-B2-BD-E0-F9-BC-F8-A1-C0-82-30-83-5F-E7-28-AC-ED-85-99-82-BE-C9-C7-8F-80-73-76-59-7F-CC-03-B0-36-E2-4F-0F-20-1B-2E-09-A0-A1-D9-93-CD-CC-DE-A1-28-CB-62-BF-D1-85-AA-73-FB-49-08-D1-E2-D2-7A-9C-89-A0-2E-74-99-DA-1E-18-73-36-69-AD-03-E7-FB-0F-D5-AD-80-6F-15-05-11-66-E9-3F-F9-A3-15-5D-CD-67-E7-75-25-DF-70-E3-A1-F5-A9-9E-E9-93-E8-5E-62-5A-33-AA-84-58-95-87-01-0C-EE-89-DD-C1-78-6C-A0-20-2B-57-18-15-97-99-9D-37-51-5D-05-C8-B4-44-11-BD-58-E2-21-9F-DE-F7-0F-57-02-7F-68-25-CF-E7-F0-FE-2A-39-83-8C-B0-3C-4B-DF-24-32-E6-F7-55-49-08-62-F8-CF-B9-A9-50-28-83-86-30-B1-8B-FC-3C-82-FA-49-13-3B-66-85-03

I try to verify the signature by three methods:
1. Session Verify (HighLevelAPI)
2. ISigner VerifySignature (BouncyCastle)
3. RSACryptoServiceProvider VerifyData (System.Security.Cryptography)

Screen shot of verify results below:
On Windows:
![image](https://cloud.githubusercontent.com/assets/20855247/21489714/96774a52-cc28-11e6-8d02-9d4371977182.png)

On Linux:
![default](https://cloud.githubusercontent.com/assets/20855247/21489754/fada1d26-cc28-11e6-83bf-fe72e89072d0.jpg)

The results of session verify are also different from the others.

**Comment by jariq** [comment]
Signature creation and verification is performed completely in unmanaged PKCS#11 library so problems like this are harder to debug but it most likely can be done if you provide additional information:

1. What device and unmanaged PKCS#11 library are you using?
2. What type of key are you using? (e.g. RSA)
3. Snippet of the problematic code including how you acquire `ObjectHandle` of private key for signature creation and `ObjectHandle` of public key for signature verification.
4. Public key or certificate with the public key that can be used for "manual" validation of signature values you provided.
5. Logs generated with [PKCS11-LOGGER located between your application and unmanaged PKCS#11 library](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/doc/TROUBLESHOOTING.md).

**Comment by cp293900** [comment]
Thanks for your tips, I try to use the other PKCS#11 library and token, all results are good. :-)
