### ISSUE TITLE
Update to PKCS#11 v2.40 errata01

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#43]
SoftHSM 2.3.0 support: https://github.com/opendnssec/SoftHSMv2/issues/130
Official headers: https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.40/headers

**Comment by pavelkhrulev** [comment]
Will you publish new release 3.4.0 with PKCS#11 v2.40 update?

**Comment by jariq** [comment]
@pavelkhrulev yes I will but I would like to finish #44 first.
