### ISSUE TITLE
info about ec key pair generation

### ISSUE THREAD

**Issue by armando-basile** [Pkcs11Interop/Pkcs11Interop#46]
Hi Jariq,
i generated some EC KEY PAIRS with brainpool 256 r1 and some private key have len=31 bytes, not 32. I saw that i sould left pad with 0x00 but is there a key attribute or mech parameter to force padding so key len is 32 always ?

i tryed to force VALUE_LEN attribute but on some keys value len is still 31 bytes, seems that hsm generate key not in according with forced VALUE_LEN attributes.

could you help me ?

**Comment by jariq** [comment]
I would suggest using `VALUE_LEN` attribute but you have already tried that. I guess it is time to ask unmanaged PKCS#11 library vendor for help.

**Comment by jariq** [comment]
@armando-basile any news on this?

**Comment by armando-basile** [comment]
Hi  Jariq,
no news, we forced left padding with 0x00 so we don't discard any generation.
