### ISSUE TITLE
info on CKA_VALUE on RSA PublicKey

### ISSUE THREAD

**Issue by armando-basile** [Pkcs11Interop/Pkcs11Interop#56]
Hi Jariq,
i trying to read public key value from an RSA key pair generated, but i have always CKA_VALUE empty. Instead if i try to generate an EC key pair, i can read public key value.

could be an HSM settings or i miss something ?

Should i consider only CKA_MODULUS as public key value ?
thanks

**Comment by jariq** [comment]
You will need to read both CKA_MODULUS and CKA_PUBLIC_EXPONENT and most likely also encode them in SubjectPublicKeyInfo or similar structure.

For example see https://github.com/Pkcs11Admin/Pkcs11Admin/blob/master/src/Pkcs11Admin/Pkcs11Slot.cs#L1036

**Comment by jariq** [comment]
@armando-basile is there any update on this? Was provided link helpful?

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
