### ISSUE TITLE
CKR_ENCRYPTED_DATA_INVALID exception cause high CPU usage

### ISSUE THREAD

**Issue by MuratGundes** [Pkcs11Interop/Pkcs11Interop#57]
Hi Jariq,

I wrote it from Stackoverflow, but I also wanted to write from here.

We are using Pkcs11Interop library for cryptography and we customize&implement Pkcs11Interop code samples for our project where [Pkcs11Interop documents](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/master/doc/CODE_SAMPLES.md). In production, not everyday but we have to restart server after CPU usage reach maximum when we get an consecutive(4 or 5 times) CKR_ENCRYPTED_DATA_INVALID exception. What cause this ? How can we fix this problem ? If you want I can share our code sample. Thanks for helping.

**Comment by jariq** [comment]
Let's continue on [stackoverflow](https://stackoverflow.com/q/45051750/3325704).
