### ISSUE TITLE
Method C_Initialize returned CKR_GENERAL_ERROR

### ISSUE THREAD

**Issue by sun2sirius** [Pkcs11Interop/Pkcs11Interop#59]
Cannot get the sample code presented in "Getting started with Pkcs11Interop" to work - getting an unhandled exception of type 'Net.Pkcs11Interop.Common.Pkcs11Exception' in Pkcs11Interop.dll. Tried x64 vs. x86, different .NET frameworks - no luck. Reinstalled the SoftHSM2 from scratch to the default location - no help. I run Windows 10 with all the latest updates. Building with VS2013, but I have the VS2015 redist installed, also I assume SoftHSM2.msi will install everything necessary. The SoftHSM2 works fine by itself. Any help is appreciated.

Turned out to be some misconfiguration of the SoftHSM2. Pointing the env var to the newly installed SoftHSM2 with empty tokens made it work. Then I copied my existing tokens over - still works. Point back to my SoftHSM2's original location - this error.

**Comment by jariq** [comment]
SoftHSM2 logs errors and other important information into windows event log. You should be able to find the real cause of the issue there.
