### ISSUE TITLE
CKM_SHA256_RSA_PKCS_PSS implementation

### ISSUE THREAD

**Issue by armando-basile** [Pkcs11Interop/Pkcs11Interop#62]
Hi Jariq,
i trying to implement sign using CKM_SHA256_RSA_PKCS_PSS mechanism but i receive always CKR_MECHANISM_PARAM_INVALID. i suspect that need to pass some other parameters to mechanism but i doesn't find any sample. Could you help me ?

**Comment by jariq** [comment]
https://github.com/jariq/Pkcs7SignatureGenerator/blob/master/src/Pkcs7SignatureGenerator/Pkcs7SignatureGenerator.cs#L338

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
