### ISSUE TITLE
Net471 app includes Pkcs11Interop.dll but tries to load Pkcs11Interop.NetStandard.dll

### ISSUE THREAD

**Issue by Timovzl** [Pkcs11Interop/Pkcs11Interop#65]
The NuGet package requires netstandard13 *or* net4. It is referenced from LibraryProject, which is netstandard2. That project, in turn, is referenced from WebProject, which is net471.

When building and running WebProject, **it outputs `Pkcs11Interop.dll`, but at runtime it tries to load `Pkcs11Interop.NetStandard.dll`**!

This can be quickly reproduced by creating the simple setup above.

Which DLL *should* be used? I would assume the netstandard one, as the direct consuming project is netstandard.

How do we get the compile time and runtime behaviors to play nice?

I have also placed this as a comment under a more general thread [here](https://github.com/dotnet/standard/issues/481), but I was unable to reproduce the problem with other NuGet packages, as they seem to always output the same DLL name.

Is it common practice to use a different file name for the netstandard DLL? Presumably this issue can be avoided by always using the same file name. (The underlying issue would remain, and is likely unrelated to Pkcs11Interop.)

**Comment by jariq** [comment]
Managed to replicate the problem. I'll come back with more details tomorrow.

**Comment by jariq** [comment]
> Which DLL should be used? I would assume the netstandard one, as the direct consuming project is netstandard.

I'd say it should use `netstandard1.3` one because your `netstandard2.0` library was compiled against it but as you can see it uses `net45` one. VS2017 tooling and NetStandard never fail to amaze me :)

> How do we get the compile time and runtime behaviors to play nice?

My first idea was to use assembly binding redirect in `web.config` and redirect `Pkcs11Interop.NetStandard.dll` to `Pkcs11Interop.dll`:

```XML
<runtime>
  <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
    <dependentAssembly>
      <assemblyIdentity name="Pkcs11Interop.NetStandard"
        publicKeyToken="c10e9c2d8c006d2a"
        culture="neutral" />
      <codeBase version="4.0.0.0" href="file:///D:/Pkcs11Interop/Issue65/ClassLibrary1/WebApplication1/bin/Pkcs11Interop.dll" />
    </dependentAssembly>
  </assemblyBinding>
</runtime>
```

It failed because of assembly name mismatch:

```
WRN: Comparing the assembly name resulted in the mismatch: NAME
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

So I tried copying `Pkcs11Interop.NetStandard.dll` to the output directory of `net471` web application in a post-build event and it was working fine for me. I consider this to be an acceptable quick-fix for now. Would this workaround work for you?

> Is it common practice to use a different file name for the netstandard DLL?

I guess it is not. This "naming convention" started with `Pkcs11Interop.Silverlight` which was originally distributed as a separate nuget package and later merged into main package. From that moment I just followed the convention with `Pkcs11Interop.Android`, `Pkcs11Interop.iOS` and later with `Pkcs11Interop.NetStandard`. I never imagined that different assembly names for individual platforms may cause any problems.

> Presumably this issue can be avoided by always using the same file name.

I'll most likely use the same filename in the future but IMO it is a significant change which should be accompanied by a major version change. It's definitely not something I'll rush to do. I'd like to think of other possible solutions first and that will take some time.

**Comment by Timovzl** [comment]
> So I tried copying Pkcs11Interop.NetStandard.dll to the output directory of net471 web application in a post-build event and it was working fine for me. I consider this to be an acceptable quick-fix for now. Would this workaround work for you?

I've used a comparable workaround: Add the NetStandard DLL as a (top-level) resource in the project, with BuildType=Resource and CopyIfNewer. That outputs it to the bin folder.

> I'll most likely use the same filename in the future but IMO it is a significant change which should be accompanied by a major version change. It's definitely not something I'll rush to do. I'd like to think of other possible solutions first and that will take some time.

Clear. Thank you!

**Comment by Goncharyk** [comment]
Hi

I'm a juniour and I try to repeat your actions, but without success. Could you please describe in more detail the steps to solve the problem.

Best Regards
Nikita

**Comment by Goncharyk** [comment]
I will also describe the steps for playback, although I'm doing the Xamarin.Mac application, I tested the same error on Windows and here are my steps:

1. Create .Net Console App 
2. Add .NetStandart library in solution
3. Add nuget package **Pkcs11Interop** to the .NetStandart library
4. Try to use this test code in library:
```
using (Pkcs11 pkcs = new Pkcs11("libPath", AppType.MultiThread))
{

}
```

**Comment by Goncharyk** [comment]
Ok, well i solve this problem on Windows Console App, but not on Mac. I copy lib **Pkcs11Interop.NetStandart.dll** and **Pkcs11Interop.NetStandart.xml** files (took them from the nuget package ) in /LibName/bin/Debug/netstandart2.0. 
But Xamarin.Mac app gives an error message here is the log file:

```
_MMP : warning MM2006: Native library 'libdl' was referenced but could not be found.
    /Library/Frameworks/Mono.framework/Commands/pkg-config --cflags mono-2
    -D_THREAD_SAFE -I/Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/lib/pkgconfig/../../include/mono-2.0  
    
    /Library/Frameworks/Mono.framework/Commands/pkg-config --variable=libdir mono-2
    /Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/lib/pkgconfig/../../lib
    
    /Library/Frameworks/Mono.framework/Commands/pkg-config --modversion mono-2
    5.4.0

....

ld: symbol(s) not found for architecture x86_64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
    
    MMP : error MM5109: Native linking failed with error code 1.  Check build log for details.
    The command exited with code 1.
    Output Item(s): _NativeLibrary=
  Done executing task "Mmp" -- FAILED.
Done building target "_CompileToNative" in project "IDReader.csproj" -- FAILED._
```

**Comment by Goncharyk** [comment]
I open discussion on Xamarin Forum: 
https://forums.xamarin.com/discussion/122198/linker-command-failed-with-exit-code-1-use-v-for-more-details#latest

**Comment by Timovzl** [comment]
I'm curious if you've decided to use the same name, or if you're expecting a generic fix for the problem.

**Comment by Goncharyk** [comment]
All works perfect here https://github.com/Pkcs11Interop/Pkcs11Interop/issues/68
