### ISSUE TITLE
Pkcs11Interop and CertEnroll

### ISSUE THREAD

**Issue by Gili-doron** [Pkcs11Interop/Pkcs11Interop#66]
Hi,

I'm using Pkcs11Interop in order to get the TokenInfo of a Smartcard.
This is working fine, but when after that I'm trying to generate PKCS10 using Microsoft CertEnroll I'm getting a "a smart card was detected but is not the one required for the current operation..." message.
When using NCryptoki it did not happen (but clearly I prefer an open source solution).
Is this a known issue?

Thanks.

The code I run -

```
public static TokenInfo GetCardSn(string readerName, string pkcs11LibraryPath)
        {
            AppType appType = AppType.SingleThreaded;
            TokenInfo selecteTokenInfo = null;
            using (Net.Pkcs11Interop.HighLevelAPI.Pkcs11 pkcs11 = new Net.Pkcs11Interop.HighLevelAPI.Pkcs11(pkcs11LibraryPath, appType))
            {
                // Find first slot with token present
                List<Slot> slots = pkcs11.GetSlotList(SlotsType.WithTokenPresent);
                
                foreach (Slot slot in slots)
                {
                    SlotInfo slotInfo = null;
                    TokenInfo tokenInfo = null;

                    try
                    {
                        slotInfo = slot.GetSlotInfo();
                        tokenInfo = slot.GetTokenInfo();
                    }
                    catch (Pkcs11Exception ex)
                    {
                        if (ex.RV != CKR.CKR_TOKEN_NOT_RECOGNIZED && ex.RV != CKR.CKR_TOKEN_NOT_PRESENT)
                            throw;
                    }

                    if (tokenInfo == null)
                        continue;

                    if (slotInfo.SlotDescription == readerName)
                    {
                        selecteTokenInfo = tokenInfo;
                        break;
                    }

                }

            }
            return selecteTokenInfo;
        }
```

And code I run which gives me the error -
```
X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);

    store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);

    foreach (X509Certificate2 mCert in store.Certificates)
    {
        //Find Container name?

        var privateKey = mCert.PrivateKey as RSACryptoServiceProvider;

        var uniqueKeyContainerName = privateKey.CspKeyContainerInfo.UniqueKeyContainerName;
        var keyContainerName = privateKey.CspKeyContainerInfo.KeyContainerName;
        var ProviderName = privateKey.CspKeyContainerInfo.ProviderName;
        // etc.
    }
```

**Comment by jariq** [comment]
It's not a known issue. IMO it's related to / caused by the smartcard middleware. You are experiencing some kind of interference between PKCS#11 implementation (which you are using via Pkcs11Interop) and CSP/minidriver implementation (which you are using via `X509Store` and other .NET classes).

Two additional questions:
1. What smartcard are you using and what middleware are you using?
2. Can you paste your previous code that uses NCryptoki and worked fine for you?

**Comment by Gili-doron** [comment]
Hi,
I'm using Athena smartcard ("Athena ASECard Crypto CSP").
I'm using their CSP "IDProtect".

the NCryptoki code - 
```
public static TokenInfo NcrypTokenInfo(string readerName)
        {
            var cryptoki = new Cryptoki("asepkcs.dll");
            int nRet = cryptoki.Initialize();
            SlotList slots = cryptoki.Slots;
            foreach (Slot slot in slots)
            {
                if (!slot.IsTokenPresent)
                {
                    Console.WriteLine("No token found in the slot: " + slot.Info.Description);
                    return null;
                }
                SlotInfo sinfo = slot.Info;
                Token token = slot.Token;
                // Prints all information relating to the token
                TokenInfo tinfo = token.Info;

                if (sinfo.Description.TrimEnd() == readerName)
                {
                    return tinfo;
                }

            }
            return null;
        }
```


Thanks.

**Comment by jariq** [comment]
In `NcrypTokenInfo` with NCryptoki you are not finalizing and unloading PKCS#11 library but in `GetCardSn` with Pkcs11Interop you are doing both things thanks to `using` clause.

Try to change

```
using (Net.Pkcs11Interop.HighLevelAPI.Pkcs11 pkcs11 = new Net.Pkcs11Interop.HighLevelAPI.Pkcs11(pkcs11LibraryPath, appType))
```

to

```
var pkcs11 = new Net.Pkcs11Interop.HighLevelAPI.Pkcs11(pkcs11LibraryPath, appType);
```

and let me know the result.

**Comment by Gili-doron** [comment]
Yep it is working now. Thanks!
It seems a bit strange because finalizing the library looks like a good practice.
Is it safe to work this way in your opinion?

Thanks.

**Comment by jariq** [comment]
You should finalize and unload the library when you are not going to work with it anymore. From application perspective, PKCS#11 library initialization and finalization are global events, so it is crucial to ensure that one thread does not finalize library while other threads are still working with it. Unless your application is long running service then you should be fine - library will be unloaded when your application is closed.
