### ISSUE TITLE
Xamarin.Mac

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#67]
*From @Goncharyk on Feb 8, 2018 10:30 AM GTM+1*

Xamarin.Mac app gives an error message here is the log file:

```
_MMP : warning MM2006: Native library 'libdl' was referenced but could not be found.
    /Library/Frameworks/Mono.framework/Commands/pkg-config --cflags mono-2
    -D_THREAD_SAFE -I/Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/lib/pkgconfig/../../include/mono-2.0  
    
    /Library/Frameworks/Mono.framework/Commands/pkg-config --variable=libdir mono-2
    /Library/Frameworks/Xamarin.Mac.framework/Versions/4.0.0.216/lib/pkgconfig/../../lib
    
    /Library/Frameworks/Mono.framework/Commands/pkg-config --modversion mono-2
    5.4.0

....

ld: symbol(s) not found for architecture x86_64
    clang : error : linker command failed with exit code 1 (use -v to see invocation)
    
    MMP : error MM5109: Native linking failed with error code 1.  Check build log for details.
    The command exited with code 1.
    Output Item(s): _NativeLibrary=
  Done executing task "Mmp" -- FAILED.
Done building target "_CompileToNative" in project "IDReader.csproj" -- FAILED._
```

I open discussion on Xamarin Forum: https://forums.xamarin.com/discussion/122198/linker-command-failed-with-exit-code-1-use-v-for-more-details#latest 

*Moved from original issue: https://github.com/Pkcs11Interop/Pkcs11Interop/issues/65*

**Comment by jariq** [comment]
Related SO question: https://stackoverflow.com/questions/48685321/linker-command-failed-with-exit-code-1-use-v-for-more-details-xamarin-mac

**Comment by jariq** [comment]
I have no previous experience with Xamarin.Mac and currently I don't even have Xamarin installed on my Mac (this might change over the weekend) so I cannot test this myself but if you are willing to you can try the following:

1. Download [source code of Pkcs11Interop](https://github.com/Pkcs11Interop/Pkcs11Interop/archive/master.zip)
2. Open file `src\Pkcs11Interop\Pkcs11Interop\Common\NativeMethods.cs` in any text editor and replace all occurrences of string `[DllImport("libdl"` with string `[DllImport("/usr/lib/libSystem.dylib"`
3. Build Pkcs11Interop library using the solution `src\Pkcs11Interop.NetStandard\Pkcs11Interop.NetStandard.sln `
4. Test this build of Pkcs11Interop in your application

**Comment by Goncharyk** [comment]
Ok, I tried to follow these steps. But the only improvement I've noticed is that the build runs without warning, but with the same errors. 
Maybe I did something wrong:
When I changed NativeMethods.cs, then I opened the solution, build the project.
Go to the bin / Release, copy Pkcs11Interop.Netstandart dll. and add it to my project.
Then i tried to start the project and got the same errors.

**Comment by jariq** [comment]
You did it right. Good job! Could you please post errors?
-- 
Kind Regards / S pozdravom

Jaroslav Imrich
http://www.jimrich.sk
jaroslav.imrich@gmail.com

**Comment by Goncharyk** [comment]
Ok, this is s a full information:

![screen shot 2018-02-09 at 12 45 31 pm](https://user-images.githubusercontent.com/30652592/36023411-60975fdc-0d9d-11e8-9981-31ebb27dc0a5.png)

**Comment by jariq** [comment]
Can you please attach build log mentioned in the error message? I guess it
will cointain more detailed information.
-- 
Kind Regards / S pozdravom

Jaroslav Imrich
http://www.jimrich.sk
jaroslav.imrich@gmail.com

**Comment by Goncharyk** [comment]
I attached the file to the message above, below the picture.

**Comment by Goncharyk** [comment]
Here is [Build Log.txt](https://github.com/Pkcs11Interop/Pkcs11Interop/files/1710797/Build.Log.txt)

**Comment by jariq** [comment]
Ok thx. I’ll get back to you in 10 hours when I’ll be back on PC.
-- 
Kind Regards / S pozdravom

Jaroslav Imrich
http://www.jimrich.sk
jaroslav.imrich@gmail.com

**Comment by jariq** [comment]
@Goncharyk I've created separate [xamarin.mac branch](https://github.com/Pkcs11Interop/Pkcs11Interop/tree/xamarin.mac) and committed two changes that might help. Please test the following:

1. Download [source code of Pkcs11Interop from xamarin.mac branch](https://github.com/Pkcs11Interop/Pkcs11Interop/archive/xamarin.mac.zip)
2. Build Pkcs11Interop library using the solution `src\Pkcs11Interop.NetStandard\Pkcs11Interop.NetStandard.sln`
3. Test this build of Pkcs11Interop in your application

**Comment by Goncharyk** [comment]
Unfortunately, I do not have a home Mac, and I can check it only on Monday. If you had the same mistakes and you solved them, then it's great

**Comment by jariq** [comment]
No problem, take all the time you need. I tested current code with a very basic cocoa application - single window with a single label displaying PKCS#11 token serial number - and it was working fine. I'll wait for your report.

**Comment by Goncharyk** [comment]
Yea, it works. Thanks!

**Comment by jariq** [comment]
Thanks for sharing the result. I'm closing this issue. Feel free to open new one if you encounter any problems.
