### ISSUE TITLE
Inconsistent assembly names in NuGet package

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#68]
NuGet package `Pkcs11Interop.4.0.0.nupkg` does not use consistent assembly names across the different platforms. This is causing assembly loading issues described in #65.

Currently the package structure looks like this:

```
lib
├───monoandroid2.3
│       Pkcs11Interop.Android.dll
├───net20
│       Pkcs11Interop.dll
├───net40
│       Pkcs11Interop.dll
├───net45
│       Pkcs11Interop.dll
├───netstandard1.3
│       Pkcs11Interop.NetStandard.dll
├───sl5
│       Pkcs11Interop.Silverlight.dll
└───xamarinios1.0
        Pkcs11Interop.iOS.dll
```

Assembly names need to be unified so the package structure looks like this:

```
lib
├───monoandroid2.3
│       Pkcs11Interop.dll
├───net20
│       Pkcs11Interop.dll
├───net40
│       Pkcs11Interop.dll
├───net45
│       Pkcs11Interop.dll
├───netstandard1.3
│       Pkcs11Interop.dll
├───sl5
│       Pkcs11Interop.dll
└───xamarinios1.0
        Pkcs11Interop.dll
```

**Comment by jariq** [comment]
Already fixed in master branch. I'll keep this issue open until updated nuget package gets released.

**Comment by cdie** [comment]
Any date when it's supposed to be released as NuGet package ? Actually, in my projet, I have to do an assembly resolve to get the correct DLL.
However, this doesn't works in remote debugging, preventing me to find a strange issue that only happens on a specific computer

**Comment by jariq** [comment]
Pkcs11Interop 4.1.0 has just been published.
