### ISSUE TITLE
Improve error message in UnmanagedException

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#69]
Error message in UnmanagedException is not human friendly:

![image](https://user-images.githubusercontent.com/1163818/36051434-688a8d52-0dea-11e8-993a-38850af6760d.png)

Even though it includes [error code](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx) it does not really help to understand the cause of the error.

**Comment by manhdd1510** [comment]
Hi jaiq! i have same issue with load SafeNet protect toolkit C
**softhsm2-x64.dll** ok 
**cryptoki.dll** fail


![1](https://user-images.githubusercontent.com/13375298/41961223-1269264c-7a1c-11e8-84b4-835b9c6a5a15.PNG)

**Comment by jariq** [comment]
I see you are the victim of these unfriendly messages too. Error code `0x0000007E` is called `ERROR_MOD_NOT_FOUND` and described as `The specified module could not be found.`

I guess you might be missing some of the dependent libraries such as C++ redistributable etc. You should consult device manual or you can try to load `cryptoki.dll` with [Dependency Walker](http://dependencywalker.com/).

**Comment by manhdd1510** [comment]
Thank jariq for reply! I will learn more about this issue.
