### ISSUE TITLE
Add Xamarin.Mac support

### ISSUE THREAD

**Issue by jariq** [Pkcs11Interop/Pkcs11Interop#74]
Xamarin.Mac support will be most likely added in the next major release. Preliminary requirements were identified in #67.

**Comment by Goncharuk-Nikita** [comment]
Hi, any updates?

**Comment by jariq** [comment]
Nope, no ETA yet.

**Comment by jariq** [comment]
New `xamarinmac2.0` platform has been added:
- Assembly for this platform is built in `Pkcs11Interop.NetStandard` solution.
- This platform is enabled only during the execution of `build-xamarinmac2.0.bat` build script.
- Build process requires `MSBuild.Sdk.Extras` nuget package to be available.
- There is no test project available for this platform.
- This platform will be released with Pkcs11Interop 5.
