### ISSUE TITLE
Token PIN dialog does not work on Linux and Mac OSX

### ISSUE THREAD

**Issue by ficnar** [Pkcs11Interop/Pkcs11Interop#91]
I have token protected by a PIN.
For use private key (signing) I call login without a password. 
_session.Login(CKU.CKU_USER, (byte[])null);

On Windows token correctly show dialog for entering a PIN.

On Linux (CentOS) token not show the dialog and return error „Invalid PIN“. When I use PIN direct in Login method, then it works properly.

On Mac OSX token show dialog, but I can not type PIN to TextBox because any inputs go to my console window that calls Login method. When I use right mouse button on PIN TextBox and use Paste for entering PIN, then it is work properly, but the dialog not closed after use OK button a created signature.

I use SafeNet Gemalto smart card with interop library eTPKCS11.

**Comment by jariq** [comment]
Any GUI shown when you call `_session.Login(CKU.CKU_USER, (byte[])null);` is implemented in unmanaged PKCS#11 library so you need to contanct SafeNet/Gemalto support regarding this issue.
