### ISSUE TITLE
Import a key -> always returns CKR_TEMPLATE_INCONSISTENT

### ISSUE THREAD

**Issue by drauch** [Pkcs11Interop/Pkcs11Interop#95]
I'm trying to import a key from an `X509Certificate2` (obtained from a PFX file) into our key store using your PKCS#11 interface like so:

    var id = ...;
    var label = ...;
    var privateKeyParams = certificate.GetRSAPrivateKey().ExportParameters(true);

    var privateKeyAttributes = new List<ObjectAttribute>();
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_ID, id));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_LABEL, label));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_PRIVATE_KEY));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_KEY_TYPE, CKK.CKK_RSA));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_TOKEN, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_PRIVATE, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_SENSITIVE, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_DECRYPT, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_SIGN, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_SIGN_RECOVER, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_UNWRAP, true));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_MODULUS, privateKeyParams.Modulus));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_PUBLIC_EXPONENT, privateKeyParams.Exponent));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_PRIVATE_EXPONENT, privateKeyParams.D));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_PRIME_1, privateKeyParams.P));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_PRIME_2, privateKeyParams.Q));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_EXPONENT_1, privateKeyParams.DP));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_EXPONENT_2, privateKeyParams.DQ));
    privateKeyAttributes.Add(new ObjectAttribute(CKA.CKA_COEFFICIENT, privateKeyParams.InverseQ));
    var privateKeyHandle = session.CreateObject(privateKeyAttributes);

Why is it returning `CKR_TEMPLATE_INCONSISTENT`? I tried all combinations and it somehow doesn't work whatever I try (when removing some stuff it returns CKR_TEMPLATE_INCOMPLETE instead...)

Can you help me? Would really appreciate it.

Best regards,
Dominik

**Comment by drauch** [comment]
Is it true that I simply can't import a private key onto the HSM? Do I really need to wrap/unwrap it? If yes, how to do so? I'm struggling with it, see also https://stackoverflow.com/questions/53745019/pkcs11-unwrap-private-key-to-hsm

**Comment by jariq** [comment]
Unfortunately PKCS#11 API does not provide details which exact attribute from supplied template caused the error but many PKCS#11 libraries support some kind of internal logging mechanism which may reveal the real cause of error. Exact steps needed to enable logging should be present in the documentation provided by the PKCS#11 library vendor.

My guess is that you're receiving `CKR_TEMPLATE_INCONSISTENT` because you are setting `CKA_SENSITIVE` to `true`. Private key imported in plain form has already lost its "sensitivity" because it was exposed to an external environment. I'm successfully using following [template][0] in Pkcs11Interop.X509Store project:

```csharp
var privateKeyAttributes = new List<ObjectAttribute>()
{
	new ObjectAttribute(CKA.CKA_CLASS, CKO.CKO_PRIVATE_KEY),
	new ObjectAttribute(CKA.CKA_TOKEN, true),
	new ObjectAttribute(CKA.CKA_PRIVATE, true),
	new ObjectAttribute(CKA.CKA_MODIFIABLE, true),
	new ObjectAttribute(CKA.CKA_LABEL, ...),
	new ObjectAttribute(CKA.CKA_ID, ...),
	new ObjectAttribute(CKA.CKA_KEY_TYPE, CKK.CKK_RSA),
	new ObjectAttribute(CKA.CKA_MODULUS, rsaPrivKeyParams.Modulus.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_PUBLIC_EXPONENT, rsaPrivKeyParams.PublicExponent.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_PRIVATE_EXPONENT, rsaPrivKeyParams.Exponent.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_PRIME_1, rsaPrivKeyParams.P.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_PRIME_2, rsaPrivKeyParams.Q.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_EXPONENT_1, rsaPrivKeyParams.DP.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_EXPONENT_2, rsaPrivKeyParams.DQ.ToByteArrayUnsigned()),
	new ObjectAttribute(CKA.CKA_COEFFICIENT, rsaPrivKeyParams.QInv.ToByteArrayUnsigned())
};
```

[0]: https://github.com/Pkcs11Interop/Pkcs11Interop.X509Store/blob/0.2.0/src/Pkcs11Interop.X509Store.Tests/CryptoObjects.cs#L158

**Comment by drauch** [comment]
I've now tried exactly your template and it doesn't work with our SafeNet Luna HSM. Same error: CKR_TEMPLATE_INCONSISTENT.

I'm actually pretty sure by now that I need to wrap the key like here: http://www.ncryptoki.com/Forums/Thread.aspx?pageid=9&t=68~-1 (see post of acab at 12/18/2012 4:55:27 PM). However, I don't know what kind of data I should encrpt and then unwrap onto the HSM, for a DES3 secret key like he did, it is easy: just use the key. But what to use for an RSA key?

Here is another clue that unwrapping is necessary: https://cloudhsm-safenet-docs.s3.amazonaws.com/007-011136-002_lunasa_5-1_webhelp_rev-a/Content/reference/cmu_importkey.htm This tool also creates a temporary wrapping key to perform the operation. Unfortunately the tool is not open source.

**Comment by drauch** [comment]
I've found the solution myself. Check out https://stackoverflow.com/questions/53745019/pkcs11-unwrap-private-key-to-hsm if you're also interested.

**Comment by aalba6675** [comment]
Hi OP @drauch, hope you don't mind if I leave this here for posterity as well.  This post is about secret keys but the same principle applies (same solution as yours).,
http://www.ncryptoki.com/Forums/Thread.aspx?pageid=9&t=68~-1

**Comment by aalba6675** [comment]
Recording here for posterity...

Session captured from a HSM when it uses vendor's own tool to import private key. As @drauch worked out, it uses `C_UnwrapKey` instead of `C_CreateObject` from PKCS#8 DER.

The attributes here may be useful if you want to see what settings are needed to make this work.

```
07:43:40 30839-1286317824:STRTGenerateKey {Sesn=1 Mech=(CKM_DES3_KEY_GEN,"<null>") AttrList={CKA_CLASS="0400000000000000" CKA_KEY_TYPE="1500000000000000" CKA_TOKEN="00" CKA_SENSITIVE="01" CKA_P
RIVATE="01" CKA_EXTRACTABLE="01" CKA_ENCRYPT="01" CKA_DECRYPT="01" CKA_SIGN="01" CKA_VERIFY="01" CKA_WRAP="01" CKA_UNWRAP="01" CKA_DERIVE="00" CKA_VALUE_LEN="1800000000000000" CKA_LABEL="CITS d
efault secret key label" } }


07:43:40 30839-1286317824:STRTEncrypt_Init {Sesn=6 Mech=(CKM_DES3_CBC_PAD,"12345678") Obj=2000002 }


07:43:40 30839-1286317824:STRTEncrypt {Sesn=6 "305f020100301006072a8648ce3d020106052b81040023044830460201010441b64a7cf25d9b7390a3c4930b7651198192ba4155582ff5bd333e21a02b58d6903d14747bdab5b34c0b37f1c974f375b904ee8e7ef3e0177d407f7b33db03d4dbfa" pusEncryptedDataLen=0x4cab8ad8 *pusEncryptedDataLen=104 }

07:43:40 30839-1286317824:STRTUnwrapKey {Sesn=6 Mech=(CKM_DES3_CBC_PAD,"12345678") Obj=2000002 "a07bb462dbc218d477d8db10239c81f5d9563e810c0debad5dbd24dd5c6ae20a8c696d355fc26ee1cdc30a219eb97e9c581585ca032f6eace5ff24f068ede0a91966bdd5f1ec480c35a3aba31899330cba46d5f70d21256b3c8e8a7fa7366a39d530520c873e9f66" AttrList={CKA_CLASS="0300000000000000" CKA_KEY_TYPE="0300000000000000" CKA_PRIVATE="01" CKA_LABEL="CITS default private key label" CKA_TOKEN="00" CKA_SENSITIVE="01" CKA_SIGN="01" CKA_DECRYPT="01" CKA_UNWRAP="01" CKA_DERIVE="01" } }

```
